### PR TITLE
Update documentation for Docker Compose v2 notes

### PR DESCRIPTION
**Pull request by cwanja**
Included note about Docker Compose v2 command formatting.

**Note** - not going to patch my own changes to master. Will await a review. It is just documentation, but still good measure 🤷🏻‍♂️

### CODE REVIEW

**Review by DrMichael — COMMENTED** [review]
Thanks. Good to note that!

**Comment by JakobLichterfeld** [comment]
Yeah, good practice to not merge your own code without review.

I vote against this change, as docker-compose is deprecated since years and only makes Docu more complex without adding value

**Comment by cwanja** [comment]
Should the note read that instead and advise individuals to update? 

Fully admit - I am still on v1.

**Comment by JakobLichterfeld** [comment]
Yeah, as V1 has end of support on July 2023

**Comment by cwanja** [comment]
On it.

**Pull request closed without merging**
