### PR TITLE
ci: add yeec and leex compilers to mix.exs

### PR DESCRIPTION
**Pull request by JakobLichterfeld**
To fix the linter warnings, see for example here: https://github.com/teslamate-org/teslamate/actions/runs/9380988328

### CODE REVIEW

**Comment by brianmay** [comment]
I suspect the problem is in compiling one/more dependencias. Can't fix it here :-(

In general I think the Elxir community aren't particularly proactive about removing compiler warnings - have a look at the compiler logs.

Although this could also be because we are using old versions of packages (I suspect probably).

It could also be sign that the packages we rely on are no longer being maintained.

**Comment by JakobLichterfeld** [comment]
At least the linter warnings dissapear with these changes.

From time to time I remember your idea of rewriting in rust.

**Comment by brianmay** [comment]
Are you sure that they disappeared?

I still see them. e.g. https://github.com/teslamate-org/teslamate/actions/runs/9382022104?pr=3941

**Comment by JakobLichterfeld** [comment]
> Are you sure that they disappeared?
> 
> I still see them. e.g. https://github.com/teslamate-org/teslamate/actions/runs/9382022104?pr=3941

You are right, damn. I looked in the single job :-(

**Pull request closed without merging**
