### PR TITLE
Use recommended format for Home Assistant MQTT sensor configuration

### PR DESCRIPTION
**Pull request by t3hk0d3**
Change documentation to offer example configuration using more robust format for MQTT sensors.
Proposed format is considered best practice by [Home Assistant documentation](https://www.home-assistant.io/integrations/mqtt/#yaml-configuration-listed-per-item)

Additionally it introduces device grouping and adds sensor availability settings.

### CODE REVIEW

**Review by Dulanic — COMMENTED** [review]
I like this, but why did you name everything teslamate_1? Either way, I dont have time to review right now, but I do like the idea behind it at least.

**Comment by t3hk0d3** [comment]
@Dulanic `teslamate_1` is used as an example because teslamate exposes cars in `teslamate/cars/1` topic.

**Comment by t3hk0d3** [comment]
Rebase against lastest `master` branch, added TPMS sensor information

**Comment by t3hk0d3** [comment]
@JakobLichterfeld can you pls check?

**Comment by JakobLichterfeld** [comment]
Thanks for rebasing. teslamate-1 as name does not seem intuitive to me.

**Comment by t3hk0d3** [comment]
> Thanks for rebasing. teslamate-1 as name does not seem intuitive to me.

@JakobLichterfeld are you talking about `unique_id`?
It is an internal identifier, and it won't be used for `entity_id` generation. https://www.home-assistant.io/integrations/sensor.mqtt/#unique_id

**Comment by JakobLichterfeld** [comment]
> I can also add `object_id` to generate nice `entity_id`, such as `tesla_charge_level`

That would be great!

**Comment by t3hk0d3** [comment]
@JakobLichterfeld I've updated PR. Please check again.

**Review by JakobLichterfeld — APPROVED** [review]
lgtm, ty. One small finding

**Review by JakobLichterfeld — CHANGES_REQUESTED** [review]

**Review by JakobLichterfeld — APPROVED** [review]
lgtm

**Pull request merged**
