### PR TITLE
[WIP] typo docs/home_assistant script.yaml->scripts.yaml

### PR DESCRIPTION
**Pull request by baylanger**
While doing my own setup, I noticed this slight typo.

### CODE REVIEW

**Comment by baylanger** [comment]
@mnadvornik fyi.

**Comment by baylanger** [comment]
I just realized this might be needed as well with automation.yaml but maybe I'm doing something wrong.

The default configuration.yaml comes with :
```
automation: !include automations.yaml
script: !include scripts.yaml
```

Perhaps those are used by the system?!?  I'll do some googling a little later.

I'm still quite knew to HA, still learning.

**Comment by baylanger** [comment]
If I set the following in `configuration.yaml`

```
automation: !include automations.yaml
script: !include scripts.yaml
automation: !include automation.yaml
script: !include script.yaml
```

This shows up :
```
2021-06-19 09:04:41 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "automation". Check lines 8 and 66
2021-06-19 09:04:41 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "script". Check lines 9 and 67
```

Based on [ha-docs|https://www.home-assistant.io/docs/configuration/splitting_configuration/]

I ended up doing this : 

```
tesla automation: !include tesla-automation.yaml
tesla script: !include tesla-script.yaml
```

Maybe it makes sense to tag those with "tesla" prefix?

**Comment by ColoradoBills** [comment]
If you copy the automation script, you get: Message malformed: expected dictionary

**Comment by kimmilde** [comment]
You cant have duplicated automation or script in your configuration. 

Use 

`automation: !include_dir_merge_list ./automasjon
`

then just make a new file teslamate.yaml with all your automations.

**Comment by Dulanic** [comment]
I am going to close this. If we need to review again, lets open a new PR as the script.yaml isn't even added to the configuration.yaml.  We probably could just add script(s).yaml to the configuatiuon.yaml. I think there has been changes since this was created so if anything, it probably needs different changes.

https://docs.teslamate.org/docs/integrations/home_assistant#configurationyaml

**Pull request closed without merging**
