### PR TITLE
Grafana 11.2.3, welcome dashboard, performance improvements, quality / consistency improvements, (re)allow dashboard editing

### LINKED ISSUE #4343: Drive Stats show high Max Speeds that are incorrect, as conversion to mph is missing
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When viewing the Drive Stats page, my Max Speed values are unusually high. They are definitely incorrect. I have not exceeded 90MPH ever and they are showing as 146, 126 and 111. 
I have looked in the Drives section and no drives go above 88.
Is there any way I can check or fix this issue?

### Expected Behavior

Accurate MAx mileage in Drive Stats page.

### Steps To Reproduce

1. Open Drive Stats Dashboard.
2. View Max Speeds (higher than expected).
3. Open Drives and sort by Max speed column. Max values do not match.

### Relevant log output

```shell
No logs seem relevant.
```

### Screenshots

brave_5PtiyqJepj
brave_eCQ3rlB26N

### Additional data

_No response_

### Type of installation

Docker

### Version

Version	1.31.1

### PR DESCRIPTION
**Pull request by swiffer**
@JakobLichterfeld - if you prefer seperate branches for some of the commits please ping me - this is a series of improvements as well as Grafana 11.2.3 incl. workaround for fit to data in maps.

- cc05438b43be5dd12ec5e3daea469b824adfe8d0, there is no editable property, allowUiUpdates instead. https://grafana.com/docs/grafana/latest/administration/provisioning/#making-changes-to-a-provisioned-dashboard
- fcbcab5b14f7d4a97f83c86cc8df70974bc3a6ca - performance improvements after #4284 , fixes: #4321 and fixes #4343 
- da8a5837d930224f161160e0f304cc3faa4e1027 - new dashboard that is configured to be the home dashboard within grafana - it changes the grafana blog and welcome section with a beautiful image (hosted at tesla.com)
- e3f6b1647df8da23bd615971f05708f727f7db23 - Grafana 11.2.3 as we cannot go to 11.3.0 for now, however i would like to keep the 11.3 PR small and some things out
- 8856e6d313d4a9e9f386fd3826cf870a2f4501c9 - simplify sql in statistics dashboard (in line with other dashboards now). i wonder why that was needed, @DrMichael, could you review please?
- cda0c451026b4bf3ffa669b1db2873a09a81136b - replace all hard-coded case when statements for km -> miles calc with convert_km @sdwalker, could you review this one?
- 0ee54f0804a59fed2fa9e12183110bdcd6f53b19 - ensure date_trunc is always applied to timestamp with timezone 
- b37c4800bc91af3323d2153c071ffef998012682 - use open street map for visited (same for all dashboards) @DrMichael, how long does it take to load?
- a748c6e0b6df4cc714af1a279b1af65ac41247e0 - adds latest github tags for telsamate-org/teslamate to welcome screen - sadly functionality of rss reader is limited currently
- 080106d73b92f51b1f39f220075adb6abe60be23 - ensure module.nix contains all settings of grafana dockerfile

@JakobLichterfeld, CHANGELOG needs some love :) you started linking to commits, should we continue doing that?

Welcome Dashboard Screenshot

grafik

### CODE REVIEW

**Comment by JakobLichterfeld** [comment]
Thank you for your work and efforts!

> if you prefer seperate branches for some of the commits please ping me

Smaller pull requests are easier to test and much easier to revert. So in general I vote for smaller pull requests, and I know there are exceptions, see our recent nix and CI rework #4219 .


> CHANGELOG needs some love :) you started linking to commits, should we continue doing that?

😄  I only link commits when I push directly to main. This is kind of bad practice (pushing directly to main), but due to our sec protections in place it is in some cases the most efficient way to fix CI issues. So in this case, I would link to the PR in several places in the changelog.

Before merging: not only do we need to test it, we also need to make sure our nix part works. It seems to work from a quick look at https://github.com/teslamate-org/teslamate/blob/d4a2718085e2e36334e2f3f720d9d7e02cd779de/nix/module.nix#L257, but we need to be sure not to lose the new dashboard when installing via nix.

**Comment by swiffer** [comment]
Nix part -> wasn't aware of that. As the dashboard is part of the internal folder that should work. However need to change editable to allowUiUpdates there as well.

Ok, will do smaller ones in the future, reverting should still be okay if not squashing commits on merge.

Needs a bit of rebasing instead then.

**Comment by swiffer** [comment]
updated the module.nix (was missing some other recent additions to the docker file as well and typo fixed)

**Comment by sdwalker** [comment]
>     * [cda0c45](https://github.com/teslamate-org/teslamate/commit/cda0c451026b4bf3ffa669b1db2873a09a81136b) - replace all hard-coded case when statements for km -> miles calc with convert_km @sdwalker, could you review this one?

Derived efficiencies are off
Can the mi columns be renamed to Distance?

Before:
image

After:
image

**Comment by swiffer** [comment]
> Derived efficiencies are off

thanks, fixed!

> Can the mi columns be renamed to Distance?

don't understand that, what columns do you mean?

**Comment by sdwalker** [comment]
> > Can the mi columns be renamed to Distance?
> 
> which columns do you mean by that?

Efficiency:
image

Trip:
image

Rename kW to Power in Trip?
image

Probably should be another pull request to fix the others
Dutch Tax
mi column -> Distance

Drive Stats
mi driven -> Distance driven
Average kWh used per day -> Average energy used per day

Drives
kWh column -> Energy

Overview
Charging kW -> Charging Power

Timeline
kWh column -> Energy

**Comment by JakobLichterfeld** [comment]
> I cannot test that here, please verify it's working correctly

tested

**Comment by swiffer** [comment]
> > > Can the mi columns be renamed to Distance?
> > 
> > 
> > which columns do you mean by that?
> 
> Efficiency: image
> 
> Trip: image
> 
> Rename kW to Power in Trip? image
> 
> Probably should be another pull request to fix the others Dutch Tax mi column -> Distance
> 
> Drive Stats mi driven -> Distance driven Average kWh used per day -> Average energy used per day
> 
> Drives kWh column -> Energy
> 
> Overview Charging kW -> Charging Power
> 
> Timeline kWh column -> Energy

yes, opened a new issue for that - I haven't touched column titles, let's change this after this PR

**Comment by JakobLichterfeld** [comment]
> * [cc05438](https://github.com/teslamate-org/teslamate/commit/cc05438b43be5dd12ec5e3daea469b824adfe8d0), there is no editable property, allowUiUpdates instead. https://grafana.com/docs/grafana/latest/administration/provisioning/#making-changes-to-a-provisioned-dashboard

> * [fcbcab5](https://github.com/teslamate-org/teslamate/commit/fcbcab5b14f7d4a97f83c86cc8df70974bc3a6ca) - performance improvements after [fix: for drives not showing if duration < 1 minute and feat: add max speed in drives dashboard #4284](https://github.com/teslamate-org/teslamate/pull/4284) , fixes: [perf: max speed and speed histogram slow in drive stats #4321](https://github.com/teslamate-org/teslamate/issues/4321) and fixes [Drive Stats show high Max Speeds that are incorrect, as conversion to mph is missing #4343](https://github.com/teslamate-org/teslamate/issues/4343)

Tested successfully.

> * [da8a583](https://github.com/teslamate-org/teslamate/commit/da8a5837d930224f161160e0f304cc3faa4e1027) - new dashboard that is configured to be the home dashboard within grafana - it changes the grafana blog and welcome section with a beautiful image (hosted at tesla.com)

Tested successfully. Nice enhancement! 

> * [e3f6b16](https://github.com/teslamate-org/teslamate/commit/e3f6b1647df8da23bd615971f05708f727f7db23) - Grafana 11.2.3 as we cannot go to 11.3.0 for now, however i would like to keep the 11.3 PR small and some things out

Tested successfully.

> * [8856e6d](https://github.com/teslamate-org/teslamate/commit/8856e6d313d4a9e9f386fd3826cf870a2f4501c9) - simplify sql in statistics dashboard (in line with other dashboards now). i wonder why that was needed, @DrMichael, could you review please?

Tested successfully, side by side with v1.31.1

> * [cda0c45](https://github.com/teslamate-org/teslamate/commit/cda0c451026b4bf3ffa669b1db2873a09a81136b) - replace all hard-coded case when statements for km -> miles calc with convert_km @sdwalker, could you review this one?

> * [0ee54f0](https://github.com/teslamate-org/teslamate/commit/0ee54f0804a59fed2fa9e12183110bdcd6f53b19) - ensure date_trunc is always applied to timestamp with timezone, fixes: [Statistics Dashboard - Time Driven is Truncated #4268](https://github.com/teslamate-org/teslamate/issues/4268)

> * [b37c480](https://github.com/teslamate-org/teslamate/commit/b37c4800bc91af3323d2153c071ffef998012682) - use open street map for visited (same for all dashboards) @DrMichael, how long does it take to load?

Really nice alignment wiht the look and feel of other dashboards. I guess we need to do a batch update of the screenshots in https://github.com/teslamate-org/teslamate/blob/a4152a23f102a01eacd969c5f5ece2f16ccd8ce9/website/docs/screenshots.mdx

> * [a748c6e](https://github.com/teslamate-org/teslamate/commit/a748c6e0b6df4cc714af1a279b1af65ac41247e0) - adds latest github tags for telsamate-org/teslamate to welcome screen - sadly functionality of rss reader is limited currently

Only point I do not like, is the "invalid date". I assue this is due to RSS:

image

> * [080106d](https://github.com/teslamate-org/teslamate/commit/080106d73b92f51b1f39f220075adb6abe60be23) - ensure module.nix contains all settings of grafana dockerfile

tested

**Comment by JakobLichterfeld** [comment]
What seems to be broken:

Charges:
v1.31.1
image

this pr:
image

**Comment by JakobLichterfeld** [comment]
Thanks for adding the No in the Charging stats:
image

**Comment by JakobLichterfeld** [comment]
Timeline:

"select last three drives" is broken

**Comment by JakobLichterfeld** [comment]
Charge details:

v1.31.1: 
image

this pr: 
image


--> no label on x axis anymore, diagram not correct and shifted

**Review by JakobLichterfeld — CHANGES_REQUESTED** [review]
Thank you again for all your hard work and efforts!

Overall lgtm. Some small findings, see my comments on PR.

**Comment by JakobLichterfeld** [comment]
Wait, what is this
image

😆

**Comment by swiffer** [comment]
@JakobLichterfeld adressed your findings (except https://github.com/teslamate-org/teslamate/pull/4338#issuecomment-2453341052). will do later together with finding of sdwalker.

**Comment by swiffer** [comment]
living in the future, that happens when you drive a tesla long enough 😆 

grafik

**Comment by JakobLichterfeld** [comment]
> What seems to be broken:
> 
> Charges:

resolved

**Comment by JakobLichterfeld** [comment]
> But now the bar diagram is not shown as the column gets to thin.

Solved
image

**Comment by JakobLichterfeld** [comment]
> Trip:
> 
> "select last three drives" is broken. Url changes correctly, but as we do not open a new tab anymore the side does not get refreshed

fixed

**Comment by JakobLichterfeld** [comment]
> @JakobLichterfeld adressed your findings (except [#4338 (comment)](https://github.com/teslamate-org/teslamate/pull/4338#issuecomment-2453341052)). will do later together with finding of sdwalker.

Perfect, ty!

**Review by JakobLichterfeld — APPROVED** [review]
lgtm (except https://github.com/teslamate-org/teslamate/pull/4338#issuecomment-2453341052)

**Comment by JakobLichterfeld** [comment]
If I'm right, the only open point is this:

> * [8856e6d](https://github.com/teslamate-org/teslamate/commit/8856e6d313d4a9e9f386fd3826cf870a2f4501c9) - simplify sql in statistics dashboard (in line with other dashboards now). i wonder why that was needed, @DrMichael, could you review please?

@DrMichael Can we get your thoughts on this?

**Comment by swiffer** [comment]
I think he commented already but the comment got lost by force push - sorry for your double work @DrMichael ...

I'll continue working after this PR is merged but wait until then to not make it bigger and bigger

**Comment by JakobLichterfeld** [comment]
So we are ready to merge. Aren't we?

**Comment by swiffer** [comment]
i had no chance yet to read the comment of @DrMichael but I would say yes. I'll take care of reverting in case he has concerns over the simplification

**Comment by JakobLichterfeld** [comment]
Rebase and merge, innit? As we didn't have "create merge commit" enabled and we do not want to squash this pr

**Comment by swiffer** [comment]
@JakobLichterfeld lgtm

**Comment by DrMichael** [comment]
> i had no chance yet to read the comment of @DrMichael but I would say yes. I'll take care of reverting in case he has concerns over the simplification

Oh, I just commented, that I introduced $__timezone__ to get the day showing up from 00:00 until 24:00 and not to show the day as in UTC. The statistics for day looked good for me with this PR, but I have no drives or charges, which are in one day with UTC and in another with my timezone. I am just on UTC+1.

So, I suggested to go ahead, if something shows up with someone with a bigger difference, we can easily revert.

**Comment by JakobLichterfeld** [comment]
perfect, ty.

**Pull request merged**
