### PR TITLE
Update statistics.json: timezone issues addressed

### PR DESCRIPTION
**Pull request by DrMichael**
Change to use $__timezone macro.

### CODE REVIEW

**Comment by JakobLichterfeld** [comment]
To test this changes, we can update our docker-compose.yml as follows (see https://docs.teslamate.org/docs/development#testing-with-our-ci-which-builds-the-docker-images-automatically-per-pr)

```
grafana:
       # image: teslamate/grafana:latest
      image: ghcr.io/teslamate-org/teslamate/grafana:pr-3862
```

**Comment by cwanja** [comment]
> To test this changes, we can update our `docker-compose.yml` as follows (see https://docs.teslamate.org/docs/development#testing-with-our-ci-which-builds-the-docker-images-automatically-per-pr)
> 
> 
> 
> ```
> 
> grafana:
> 
>        # image: teslamate/grafana:latest
> 
>       image: ghcr.io/teslamate-org/teslamate/grafana:pr-3862
> 
> ```
> 
> 
> 
> do a `docker compose pull` followed by a `docker compose up -d` afterwards

Going to ask a dumb question here (forgive me). How would you remove these 'test' images once you are done testing? Or does it not retain them somehow? Mainly thinking space on my Pi.

**Comment by cwanja** [comment]
Wondering of "timezone" in all of our dashboard JSONs should be "browser".
https://github.com/search?q=repo%3Ateslamate-org%2Fteslamate%20timezone&type=code

**Comment by cwanja** [comment]
This does not work for me. Or I am not pulling the image correctly 🤷🏻‍♂️ I continue to see the timezone dropdown. Looking through the JSON, I do not see the iteration to verify it was upped. Followed the guidance above:
```
  grafana:
#    image: teslamate/grafana:latest
    image: ghcr.io/teslamate-org/teslamate/grafana:pr-3862
```

But still not working. Tried to prune all of my docker images with `docker image prune -a` and `docker container prune` to no luck.

**Comment by JakobLichterfeld** [comment]
> How would you remove these 'test' images once you are done testing? Or does it not retain them somehow? Mainly thinking space on my Pi.

Good point. There are several ways, but if you want to remove dangling images, this would be safest imo:

> docker image prune -a
> 
> WARNING! This will remove all images without at least one container associated to them.

see https://docs.docker.com/reference/cli/docker/image/prune/

**Comment by DrMichael** [comment]
This needs to be tested still...
Edge cases are drives and charges between midnight UTC and midnight local time.

**Comment by DrMichael** [comment]
> Wondering if "timezone" in all of our dashboard JSONs should be "browser". https://github.com/search?q=repo%3Ateslamate-org%2Fteslamate%20timezone&type=code

AFAICS one is browser, the others are empty, probably also meaning browser.

**Comment by DrMichael** [comment]
I am a bit struggling here... I have two charges: in the database:
```
 id  |       start_date
-----+-------------------------
 576 | 2024-01-20 21:37:50.375
 577 | 2024-01-20 23:01:09.237
(2 rows)
```
Since it is UTC and my local time is Europe/Berlin, the second was indeed on 2024-01-21 00:01 and should show up for the 2024-01-21.

Relevant query:
```
WITH data AS (
  SELECT
    charging_processes.*,
    date_trunc('$period', TIMEZONE('$__timezone', start_date)) as local_period
    FROM charging_processes)
SELECT
  EXTRACT(EPOCH FROM date_trunc('$period', TIMEZONE('$__timezone', local_period)))*1000 AS date_from,
  EXTRACT(EPOCH FROM date_trunc('$period', TIMEZONE('$__timezone', local_period) + ('1 ' || '$period')::INTERVAL))*1000 AS date_to,
  CASE '$period'
    WHEN 'month' THEN to_char(local_period, 'YYYY Month')
    WHEN 'year' THEN to_char(local_period, 'YYYY')
    WHEN 'week' THEN 'week ' || to_char(local_period, 'WW') || ' starting ' || to_char(local_period, 'YYYY-MM-DD')
    ELSE to_char(local_period, 'YYYY-MM-DD')
  END AS display,
  local_period AS date,
  sum(greatest(charge_energy_added,charge_energy_used)) AS sum_consumption_kwh,
  sum(greatest(charge_energy_added,charge_energy_used)) / count(*) AS avg_consumption_kwh,
  sum(cost) AS cost_charges,
  count(*) AS cnt_charges
FROM data WHERE
  car_id = $car_id AND
  $__timeFilter(start_date) AND
  (charge_energy_added IS NULL OR charge_energy_added > 0.1)
GROUP BY date
ORDER BY date
```
I tried to apply the timezone correction to the other, but it did not help. Any thoughts?

**Comment by DrMichael** [comment]
> This does not work for me. Or I am not pulling the image correctly 🤷🏻‍♂️ I continue to see the timezone dropdown. Looking through the JSON, I do not see the iteration to verify it was upped.

Same here. But the images have been produced...

**Comment by cwanja** [comment]
> > This does not work for me. Or I am not pulling the image correctly 🤷🏻‍♂️ I continue to see the timezone dropdown. Looking through the JSON, I do not see the iteration to verify it was upped.
> 
> 
> 
> Same here. But the images have been produced...

@JakobLichterfeld is there something we are missing? Does it go in Grafana or TeslaMate service?

**Comment by JakobLichterfeld** [comment]
> @JakobLichterfeld is there something we are missing? Does it go in Grafana or TeslaMate service?

Not really. It must be included in the grafana image.
It on my side as well, and your changes seems to be not correctly reflected in the Grafana image. Currently, I'm out of time to dig deeper. (https://github.com/teslamate-org/teslamate/issues/3857#issuecomment-2068640395)

**Comment by DrMichael** [comment]
I'd like some more testing from users with significant timezone difference to UTC, e.g. UTC+-5 or more...

**Comment by cwanja** [comment]
> I'd like some more testing from users with significant timezone difference to UTC, e.g. UTC+-5 or more...

UTC -5 (or 6 depending on the time of year) hours and just tested. 
1. Timezone dropdown is removed. 
2. Verified that it starts at 12AM in month and day view. 
3. Month view looks correct.
4. Clicking on a day, the timeframe is midnight to midnight of the selected day.

One item I did find, testing a use-case from @towster - it seems the **Drives** dashboard filters out (either) zero duration or zero distance drives. I saw this when comparing the filtered Drives dashboard versus the same day Trip dashboard links off the Statistic page. This might be by design.

**Comment by cwanja** [comment]
I am approving and merging. Great working @DrMichael and thank you 😄

**Comment by DrMichael** [comment]
> One item I did find, testing a use-case from @towster - it seems the **Drives** dashboard filters out (either) zero duration or zero distance drives. I saw this when comparing the filtered Drives dashboard versus the same day Trip dashboard links off the Statistic page. This might be by design.

Right, it filters out also drives with duration_min=0 although there is distance>0. I proposed to show those also on the Drives dashboard in https://github.com/teslamate-org/teslamate/pull/3867

**Comment by JakobLichterfeld** [comment]
@DrMichael Seems like there is an issue with this dashboard now:

> teslamate_grafana    | logger=provisioning.dashboard type=file name=teslamate t=2024-05-20T13:33:21.500815425Z level=error msg="failed to save dashboard" file=/dashboards/statistics.json error="could not resolve dashboards:uid:1EZnXszMl: Dashboard not found"

**Comment by DrMichael** [comment]
Where does that come from? The build? Not sure, what that uid issue means...
(After a pull for edge I am still on 1.28.6-dev, might be an issue with my installation again...)

**Comment by JakobLichterfeld** [comment]
> @DrMichael Seems like there is an issue with this dashboard now:

> Where does that come from?

Seems to be a dangling container issue on my end, grafana was on 1.29.1 and teslamate was on 1.28.5 hence the mismatch.
Sorry for the inconvenience

**Comment by cwanja** [comment]
@DrMichael I am still seeing the timezone in 1.29.1 and it defaults to Berlin. Is anyone else seeing this? @JakobLichterfeld @jheredianet 
Screenshot 2024-05-29 at 8 51 35 PM

**Comment by DrMichael** [comment]
Hmmm, looks good for me. You are running grafana:latest or grafana:edge?

I had a terrible time some weeks ago to get rid of old images. Perhaps try to purge all images of grafana and repull it.

**Comment by cwanja** [comment]
Not on edge. Running latest across all images. Just updated to 1.29.1 last night.

**Comment by JakobLichterfeld** [comment]
> @DrMichael I am still seeing the timezone in 1.29.1 and it defaults to Berlin. Is anyone else seeing this? @JakobLichterfeld @jheredianet 

Can confirm Timezone setting is still there with 1.29.1

**Comment by DrMichael** [comment]
Hmmm, that is wierd. I removed all teslamate and grafana images, did a fesh pull. And have the new version...

**Comment by DrMichael** [comment]
The new one uses the new `$__timezone` variable. The old one probably has Europe/Berlin in it.

**Comment by cwanja** [comment]
image
Looks like it is still there. This at least from the live Grafana interface. Not sure how to dive into the code in the Docker container specifically (if necessary).

**Comment by DrMichael** [comment]
The screenshots are from github master?
You can check in the image. It is in /dashboards.

**Comment by cwanja** [comment]
Screenshots from my Grafana installation. GitHub master looks correct. Which makes no sense why the timezone is lingering.

**Comment by cwanja** [comment]
A full sequence of the following (manually, not scripted) did not resolve the issue. Still seeing the timezone dropdown in the Statistics dashboard.

```
docker compose down
docker system prune -a
docker compose pull
docker compose up -d
```

**Comment by DrMichael** [comment]
@cwanja After the `docker system prune -a` what gives `docker image ls`?

**Comment by cwanja** [comment]
```
teslamate/teslamate | latest | b13a8634a4d0
teslamate/grafana     | latest | 6655a417b9c7
```

**Comment by DrMichael** [comment]
So, still there... Can you remove them? `docker image rm ...`

**Comment by cwanja** [comment]
What exactly am I removing? I thought these were the latest images?

**Comment by DrMichael** [comment]
Well, perhaps not. So, I would remove all teslamate and grafana images and repull them...

**Comment by cwanja** [comment]
"Perhaps not" is a really interesting take on an upgrade. I perform the software upgrade, but also "perhaps not" 😂 

Will give it a whirl this evening.

**Comment by DrMichael** [comment]
Is there any way to dive into the image on gihub? To check the json?

**Comment by cwanja** [comment]
> You can compare the checksums to be sure. But anyways, the issue is still present in 1.29.1

How do we get the checksums from the images in GitHub? Can we start posting that in the release notes?

**Comment by cwanja** [comment]
I nuked the Grafana image first and then ran a `compose`. 19 new Grafana layers were grabbed (assuming those "layers" are dashboards). Checked Statistics and still facing the issue, drop down is present and defaults to Berlin.

```
pi@teslapi:~/Documents/teslamate $ docker rmi 6655a417b9c7
Untagged: teslamate/grafana:latest
Untagged: teslamate/grafana@sha256:6ab79a7c7c2f71b65a3e21ed63aa204fbfd5c34db1737f7c939e7887f42e4836
Deleted: sha256:6655a417b9c7cd37fb941ea96b152612a42872ac71b099e8ae0780ebe53a7b43
Deleted: sha256:60242f89f2d021e534c5690993707b9d0a3b140020f9065b9b8344d25a1319eb
Deleted: sha256:befb40b508a023e4075cc1b5ed425b0bf2525f6469172053202fb529071cc146
Deleted: sha256:5a5b99f7c1423e9128ea56ce773d1b1611b51ab730782e0c5e7d2a8fb239621f
Deleted: sha256:1a0b21fda217a00d2d1da7ef98c24f5b51ebb9d1d3e33c0cab22367f4ac5395d
Deleted: sha256:c2acc0bd9c3be8da4a216bcd1f9cb3c07acab46dadaf28b90e3522871fd192c3
Deleted: sha256:372506bb6f768715f6bb3304cb399b73c8d59891714b9ae67f2d3e1f175d2edc
Deleted: sha256:2d7a1635b9dbe3e307aa2cd72a640dd31b68f0c880ae19d42e7ec51f32b37f49
Deleted: sha256:b13b3a2c45d6a1228c6155abdb4c744f9a600350957f8b9980cd892ea3163fd8
Deleted: sha256:c5b1691094bf403060d4c64f5ee9cbf77785cc72d659e685be01ded4ff527d7d
Deleted: sha256:257f46415e954442c0701d5f55d3e996d7e042526418f9f96431779ea4f21a2d
Deleted: sha256:ccaf1d9d4b7d3fbb857cbbb5ff0a487acd99b2583146328b64a2f70ffd568805
Deleted: sha256:440cfe143acaf50faa4f186f4b186a82f3d285006cec8da02dbcd5d5b228f7b2
Deleted: sha256:8b1286894f404dbb550d00050b65900e76148b8a894a1343032863a52b8231ba
Deleted: sha256:409bad753551c5c39cdbc25a3ef11d460770d8e5cd1897a243bcffbefddabd91
Deleted: sha256:627775cae66e612ad8479f2756e49c8aeba6aa7af22d5398f585d8639846cc74
Deleted: sha256:82cba545e3085b5d5ed3fdeaff29fbb6e009a0d1b57c75185240ddd21c7ed71a
Deleted: sha256:99869a6942a9942b7468700df18f73bc141b7c996438a59fa87f1296b9f0cfb8
Deleted: sha256:452c41d928afb1dfd08452e591c67b40dcfe8b0429736b97dcc6e4c3e545e49f
pi@teslapi:~/Documents/teslamate $ docker compose up -d
[+] Running 19/19
 ✔ grafana 18 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled         108.3s 
   ✔ fda0ff469afd Pull complete                                            2.2s 
   ✔ 949ba9e604ac Pull complete                                            1.1s 
   ✔ 57ec68305c19 Pull complete                                            2.0s 
   ✔ e1ca30b94fb8 Pull complete                                            2.4s 
   ✔ 14f88aa4de51 Pull complete                                            3.5s 
   ✔ 866fdb0f4681 Pull complete                                            3.4s 
   ✔ a7d444ebc6d7 Pull complete                                           22.4s 
   ✔ c0b7609d615f Pull complete                                           21.7s 
   ✔ 4d7e37de32ec Pull complete                                            4.8s 
   ✔ 43862b0c980e Pull complete                                            6.2s 
   ✔ 12d11d9f099b Pull complete                                            7.6s 
   ✔ 976075b6430d Pull complete                                            9.1s 
   ✔ 9c1df6db59fe Pull complete                                           10.5s 
   ✔ ed0ce2ddf555 Pull complete                                           12.2s 
   ✔ 16e197c14a1c Pull complete                                           13.4s 
   ✔ 674f40dd44a1 Pull complete                                           14.7s 
   ✔ 1ce2c119b02a Pull complete                                           16.0s 
   ✔ e7a04f660818 Pull complete                                           21.4s 
[+] Running 4/5
 ⠸ Network teslamate_default        Created                               33.3s 
 ✔ Container teslamate-teslamate-1  S...                                  31.6s 
 ✔ Container teslamate-mosquitto-1  S...                                  31.4s 
 ✔ Container teslamate-database-1   St...                                 32.4s 
 ✔ Container teslamate-grafana-1    Sta...                                31.4s 
pi@teslapi:~/Documents/teslamate $ 
```

Decided to nuke **both** Grafana and TeslaMate to test. No change.

```
pi@teslapi:~/Documents/teslamate $ docker rmi b13a8634a4d0, 6655a417b9c7
Untagged: teslamate/grafana:latest
Untagged: teslamate/grafana@sha256:6ab79a7c7c2f71b65a3e21ed63aa204fbfd5c34db1737f7c939e7887f42e4836
Deleted: sha256:6655a417b9c7cd37fb941ea96b152612a42872ac71b099e8ae0780ebe53a7b43
Deleted: sha256:60242f89f2d021e534c5690993707b9d0a3b140020f9065b9b8344d25a1319eb
Deleted: sha256:befb40b508a023e4075cc1b5ed425b0bf2525f6469172053202fb529071cc146
Deleted: sha256:5a5b99f7c1423e9128ea56ce773d1b1611b51ab730782e0c5e7d2a8fb239621f
Deleted: sha256:1a0b21fda217a00d2d1da7ef98c24f5b51ebb9d1d3e33c0cab22367f4ac5395d
Deleted: sha256:c2acc0bd9c3be8da4a216bcd1f9cb3c07acab46dadaf28b90e3522871fd192c3
Deleted: sha256:372506bb6f768715f6bb3304cb399b73c8d59891714b9ae67f2d3e1f175d2edc
Deleted: sha256:2d7a1635b9dbe3e307aa2cd72a640dd31b68f0c880ae19d42e7ec51f32b37f49
Deleted: sha256:b13b3a2c45d6a1228c6155abdb4c744f9a600350957f8b9980cd892ea3163fd8
Deleted: sha256:c5b1691094bf403060d4c64f5ee9cbf77785cc72d659e685be01ded4ff527d7d
Deleted: sha256:257f46415e954442c0701d5f55d3e996d7e042526418f9f96431779ea4f21a2d
Deleted: sha256:ccaf1d9d4b7d3fbb857cbbb5ff0a487acd99b2583146328b64a2f70ffd568805
Deleted: sha256:440cfe143acaf50faa4f186f4b186a82f3d285006cec8da02dbcd5d5b228f7b2
Deleted: sha256:8b1286894f404dbb550d00050b65900e76148b8a894a1343032863a52b8231ba
Deleted: sha256:409bad753551c5c39cdbc25a3ef11d460770d8e5cd1897a243bcffbefddabd91
Deleted: sha256:627775cae66e612ad8479f2756e49c8aeba6aa7af22d5398f585d8639846cc74
Deleted: sha256:82cba545e3085b5d5ed3fdeaff29fbb6e009a0d1b57c75185240ddd21c7ed71a
Deleted: sha256:99869a6942a9942b7468700df18f73bc141b7c996438a59fa87f1296b9f0cfb8
Deleted: sha256:452c41d928afb1dfd08452e591c67b40dcfe8b0429736b97dcc6e4c3e545e49f
pi@teslapi:~/Documents/teslamate $ docker rmi b13a8634a4d0
Untagged: teslamate/teslamate:latest
Untagged: teslamate/teslamate@sha256:7c833ef13585b46339b778bb974fa6ea0f908cb7b9d1a62b41aef694bfdb9ca0
Deleted: sha256:b13a8634a4d05d890f4f4bc467389fca0ed59d2216c049568c6146fc83b5865a
Deleted: sha256:dc89509f4b33ffb5002f3b3269736c2cee7538120b168cf13430b35bd06ad07a
Deleted: sha256:764babcaa369c6676cf0801867d23e5e05d779849a965fa56c8afec55c3c7ad7
Deleted: sha256:882ebbd0c74e6d309db09edfebfc2faf36b1347f6985d082366e9ca78a3976a8
Deleted: sha256:4e1234c0c179060cf8627aaa268bb1936510d0af7a13fc77baf44a67a2e31a27
Deleted: sha256:9d996fea22c2d55c9254ea1e0fb613d132d6e222bcc1771932a7e11900a63ce5
pi@teslapi:~/Documents/teslamate $ docker compose up -d
[+] Running 26/26
 ✔ teslamate 6 layers [⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                   119.6s 
   ✔ 3b9aff019fd4 Already exists                                                                          0.0s 
   ✔ ae889eac3453 Pull complete                                                                          43.7s 
   ✔ 7b5a07871c17 Pull complete                                                                          26.9s 
   ✔ 07943bbc416a Pull complete                                                                          30.3s 
   ✔ 42d684c4e5a5 Pull complete                                                                          59.7s 
   ✔ 3c86c925d10c Pull complete                                                                          30.5s 
 ✔ grafana 18 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                        139.1s 
   ✔ fda0ff469afd Pull complete                                                                           2.4s 
   ✔ 949ba9e604ac Pull complete                                                                           1.5s 
   ✔ 57ec68305c19 Pull complete                                                                           2.2s 
   ✔ e1ca30b94fb8 Pull complete                                                                           2.6s 
   ✔ 14f88aa4de51 Pull complete                                                                           3.4s 
   ✔ 866fdb0f4681 Pull complete                                                                           3.6s 
   ✔ a7d444ebc6d7 Pull complete                                                                          27.6s 
   ✔ c0b7609d615f Pull complete                                                                          19.6s 
   ✔ 4d7e37de32ec Pull complete                                                                           4.9s 
   ✔ 43862b0c980e Pull complete                                                                           6.5s 
   ✔ 12d11d9f099b Pull complete                                                                           8.1s 
   ✔ 976075b6430d Pull complete                                                                           9.7s 
   ✔ 9c1df6db59fe Pull complete                                                                          11.2s 
   ✔ ed0ce2ddf555 Pull complete                                                                          12.5s 
   ✔ 16e197c14a1c Pull complete                                                                          13.8s 
   ✔ 674f40dd44a1 Pull complete                                                                          15.0s 
   ✔ 1ce2c119b02a Pull complete                                                                          16.2s 
   ✔ e7a04f660818 Pull complete                                                                          25.2s 
[+] Running 4/5
 ⠹ Network teslamate_default        Created                                                              11.1s 
 ✔ Container teslamate-teslamate-1  Started                                                              10.2s 
 ✔ Container teslamate-grafana-1    Started                                                               9.9s 
 ✔ Container teslamate-database-1   Started                                                              10.3s 
 ✔ Container teslamate-mosquitto-1  Started                                                              10.2s 
pi@teslapi:~/Documents/teslamate $ 
```

**Comment by cwanja** [comment]
How do we want to continue testing? @DrMichael - what if you nuke _your_ images and test? Could it be that a change you made is lingering in your images? Should we formally open an issue at this point?

**Comment by JakobLichterfeld** [comment]
> How do we get the checksums from the images in GitHub?

You mean Docker Hub? https://hub.docker.com/r/teslamate/teslamate/tags

**Comment by JakobLichterfeld** [comment]
> How do we want to continue testing? @DrMichael - what if you nuke _your_ images and test? Could it be that a change you made is lingering in your images? Should we formally open an issue at this point?

As I said, issue is present in TelsaMate 1.29.1 and Teslamate Grafana 1.29.1 
@DrMichael does not have the issue as he altered his json file locally I assume which did not got overwirtten.

**Comment by DrMichael** [comment]
> > How do we want to continue testing? @DrMichael - what if you nuke _your_ images and test? Could it be that a change you made is lingering in your images? Should we formally open an issue at this point?
> 
> As I said, issue is present in TelsaMate 1.29.1 and Teslamate Grafana 1.29.1 @DrMichael does not have the issue as he altered his json file locally I assume which did not got overwirtten.

No, of course I made the changes in a separate json... in a different folder.

Ok:
```
michael@amigo <~> docker image ls
REPOSITORY         TAG       IMAGE ID       CREATED       SIZE
michael@amigo <~>

```
Then pull and up:
```
michael@amigo <~/teslamate> docker compose pull
[+] Pulling 56/5
 ✔ database Pulled                                                                                                                              78.9s
 ✔ portainer Pulled                                                                                                                             21.2s
 ✔ mosquitto Pulled                                                                                                                             58.5s
 ✔ teslamate Pulled                                                                                                                             65.6s
 ✔ grafana Pulled                                                                                                                               49.6s
michael@amigo <~/teslamate> docker compose up -d
[+] Running 6/6
 ✔ Network teslamate_default        Created                                                                                                      0.1s
 ✔ Container teslamate-grafana-1    Started                                                                                                      0.9s
 ✔ Container teslamate-teslamate-1  Started                                                                                                      0.6s
 ✔ Container teslamate-database-1   Started                                                                                                      0.6s
 ✔ Container teslamate-portainer-1  Started                                                                                                      0.9s
 ✔ Container teslamate-mosquitto-1  Started                                                                                                      0.7s
michael@amigo <~/teslamate>

```
No drop down:
image

@JakobLichterfeld when you say, it is present in 1.29.1 and it is not in https://github.com/teslamate-org/teslamate/blob/master/grafana/dashboards/statistics.json, then the build failed. But does not explain, why I see the modification...

**Comment by JakobLichterfeld** [comment]
> @JakobLichterfeld when you say, it is present in 1.29.1 and it is not in https://github.com/teslamate-org/teslamate/blob/master/grafana/dashboards/statistics.json, then the build failed. But does not explain, why I see the modification...

Exactly. 
I use ARMv7 image. Just changed grafana image to 1.29.1 instead of latest and dropdown is still there

@swiffer do you have any idea?

**Comment by cwanja** [comment]
> > How do we get the checksums from the images in GitHub?
> 
> 
> 
> You mean Docker Hub? https://hub.docker.com/r/teslamate/teslamate/tags

I'll have to check these when I get back.

**Comment by JakobLichterfeld** [comment]
> > > How do we get the checksums from the images in GitHub?
> > 
> > 
> > You mean Docker Hub? https://hub.docker.com/r/teslamate/teslamate/tags
> 
> I'll have to check these when I get back.

Pay attention, there are several SHA 256 sums from docker images, so docker hub displays the digest SHA 256 from what I know

**Comment by swiffer** [comment]
can you try pruning the grafana data volume and then restart with 1.29.1?

(warning: this would remove any additional dashboards / config done manually in grafana)

trying teslamate/grafana:latest gives me a dashboard without Europe/Berlin but making use of $__timezone instead.

maybe the change in UID of the dashboard caused an issue?

**Comment by swiffer** [comment]
any hints in the logs of your grafana container logs ? `docker logs teslamate-grafana-1`

**Comment by JakobLichterfeld** [comment]
So force deleting grafana image didn't work as reported before. No hints in log. 

Removing the teslamate-grafana-data volume solved it, grafana is not reachable anymore after a fresh `docker compose up -d`, even if the volume has been created :-)

**Comment by DrMichael** [comment]
Interesting. The volume holds /var/lib/grafana, but the jsons are in /dashboards...

**Comment by swiffer** [comment]
What happens when manually modifying provisioned dashboards within grafana?

**Comment by cwanja** [comment]
Finally resolved (for me) in 1.29.2 🎉

**Pull request merged**
