### PR TITLE
perf: improve performance in drive stats after #4284

### LINKED ISSUE #4321: perf: max speed and speed histogram slow in drive stats
The max speed and speed histogram introduced by #4253 is slow on slow hw

### Type of installation

Docker

### Version

v1.31.1

### PR DESCRIPTION
**Pull request by swiffer**
fixes #4321

@JakobLichterfeld - max speed should be blazing fast but i guess speed histogram is still not performing best, right?

### CODE REVIEW

**Comment by JakobLichterfeld** [comment]
Thanks, will test vy tomorrow

**Comment by JakobLichterfeld** [comment]
> max speed should be blazing fast but i guess speed histogram is still not performing best, right?

Tested and yes, max speed is instant, histogram takes ~5 seconds. Speed histogram in drive details is instant

**Comment by swiffer** [comment]
Yes, let me see later today if we can improve further, within drive details data size is way smaller so longer runtime is expected...

**Review by JakobLichterfeld — APPROVED** [review]

**Comment by swiffer** [comment]
closed as included in #4299

**Pull request closed without merging**
