### PR TITLE
Add endpoints parameter

### PR DESCRIPTION
**Pull request by jsight**

### CODE REVIEW

**Comment by jsight** [comment]
This seems a little hacky to me, but it does work around the problem.

**Comment by maerco** [comment]
I tested on my deploy and it fix also my model 3 recently updated to 2023.38.4

**Comment by brontide** [comment]
This solved data loss after installation of 2023.38.4 on my Model Y.

**Comment by finnysamuel** [comment]
Thanks for the patch.. It worked - MYLR 23.38.4

**Comment by viorelovidiu** [comment]
> This seems a little hacky to me, but it does work around the problem.

Hi, sorry being numb but how do I deploy this patch? I do have a Synology NAS with docker container. Thank you!

**Comment by jsight** [comment]
Change has been pushed to docker here: https://hub.docker.com/repository/docker/jsightler/teslamate/general

Also updated to (hopefully) be backward compatible and less crashy. :)

**Comment by swiffer** [comment]
Using query param with get instead of encoding the params yourself

https://github.com/elixir-tesla/tesla?tab=readme-ov-file#direct-usage

**Comment by blexter** [comment]
@adriankumpf 
I would really appreciate if this PR could be approved and merged into the official release. 🙏🙏🙏

**Comment by jsight** [comment]
@swiffer Good idea, thank you!

**Comment by marcbaier** [comment]
would be great if someone could announce it here when the update is available in the Teslamate:latest version. thanks so much !

**Comment by marcbaier** [comment]
> Change has been pushed to docker here: https://hub.docker.com/repository/docker/jsightler/teslamate/general
> 
> Also updated to (hopefully) be backward compatible and less crashy. :)

If I would like to use this update / patch and install it on my docker installation on my synology nas, can I just install it in docker by selecting my current teslamate/latest container and then selecting "import" "add from URL" ?

**Comment by blexter** [comment]
@jsight 
Getting "Internal Server Error" regularly since updated to this fix.

**Comment by brontide** [comment]
@blexter You don't indicate if you are seeing that error in the browser or the logs.  This code change is tiny and should have zero impact on the front-end of Teslamate where you might see errors in the browser.  If it's in the logs please post the complete error messages so that they can be reviewed.

**Comment by blexter** [comment]
> @blexter You don't indicate if you are seeing that error in the browser or the logs. This code change is tiny and should have zero impact on the front-end of Teslamate where you might see errors in the browser. If it's in the logs please post the complete error messages so that they can be reviewed.

Checked the logs, not 100% sure what's sensitive data, so I might removed "to much", tell me if so and I can somehow send missing info.

2023-11-01 09:02:12.741 [error] Task #PID<0.3967.0> started from TeslaMate.Vehicles terminating
** (KeyError) key :drive_state not found in: %TeslaApi.Error{
  reason: :unknown,
  message: "{\"error\": \"Get \\\"http://localhost:7654/vehicle_data?slow_query_time=15&headers%5BX-Request-Timeout%5D=5&let_sleep=true&user_command=true\\\": EOF\"}",
  env: %Tesla.Env{
    method: :get,
    url: "https://owner-api.teslamotors.com/api/1/vehicles/1234567890/vehicle_data",
    query: [],
    headers: [
      {"x-xss-protection", "1; mode=block"},
      {"x-txid", "1234567890"},
      {"content-type", "application/json; charset=utf-8"},
      {"x-request-id", "1234567890"},
      {"content-length", "219"},
      {"x-envoy-upstream-service-time", "1336"},
      {"date", "Wed, 01 Nov 2023 08:02:12 GMT"},
      {"server", "envoy"},
      {"x-frame-options", "DENY"},
      {"x-content-type-options", "nosniff"},
      {"strict-transport-security", "max-age=31536000; includeSubDomains"},
      {"cache-control", "no-cache, no-store, private, s-max-age=0"}
    ],
    body: %{
      "error" => "{\"error\": \"Get \\\"http://localhost:7654/vehicle_data?slow_query_time=15&headers%5BX-Request-Timeout%5D=5&let_sleep=true&user_command=true\\\": EOF\"}",
      "error_description" => "",
      "response" => nil
    },
    status: 540,
    opts: [
      access_token: "abcdef1234567890"
    ],
    __module__: TeslaApi,
    __client__: %Tesla.Client{fun: nil, pre: [], post: [], adapter: nil}
  }
}
    (teslamate 1.28.0-dev) lib/tesla_api/vehicle.ex:59: TeslaApi.Vehicle.get_with_state/2
    (teslamate 1.28.0-dev) lib/teslamate/api.ex:299: TeslaMate.Api.preload_vehicle/2
    (elixir 1.15.6) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.15.6) lib/task/supervised.ex:36: Task.Supervised.reply/4
Function: &:erlang.apply/2
    Args: [#Function<2.69151209/1 in TeslaMate.Api.handle_result/3>, [%TeslaApi.Vehicle{id: 1234567890, vehicle_id: 1234567890, vin: "1234567890", tokens: ["1234567890", "1234567890"], state: "online", option_codes: [""], in_service: false, display_name: "Model S", color: nil, calendar_enabled: true, backseat_token: nil, backseat_token_updated_at: nil, api_version: 67, charge_state: nil, climate_state: nil, drive_state: nil, gui_settings: nil, vehicle_config: nil, vehicle_state: nil}]]
2023-11-01 09:02:18.157 [notice] Application teslamate exited: shutdown
Kernel pid terminated (application_controller) ("{application_terminated,teslamate,shutdown}")

Crash dump is being written to: erl_crash.dump...done

**Comment by DrMichael** [comment]
@adriankumpf Given, that without that PR teslamate is broken, we need this PR incorporated. If you don't have the time, your opinion in https://github.com/adriankumpf/teslamate/discussions/3384 would be very much appreciated.
We don't probably jump to a forked teslamate.

**Comment by tpd-opitz** [comment]
How can I apply the change locally to my teslamate instance until the this PR is merged?   
I thought of adding `RUN` directive to my dockerfile to apply the change  using `sed` like suggested [here] (https://stackoverflow.com/a/27714071) but I cant find the file `vehicle.ex` within the container...

**Comment by sargue** [comment]
> How can I apply the change locally to my teslamate instance until the this PR is merged? I thought of adding `RUN` directive to my dockerfile to apply the change using `sed` like suggested [here] (https://stackoverflow.com/a/27714071) but I cant find the file `vehicle.ex` within the container...

Well, you have several options.

The simple one is to trust the patched docker image that the same author of this PR uploaded to Docker Hub.

Another option is to build yourself a patched image, which seems to be what you're trying.

NOTE: I haven't tried any of this myself, my car is still on a previous version. Be very careful, do a full backup before you change anything.

If you have access to the command line and `docker`, and you have `git` installed (or you can install it), you can just build a local image with the change, then change the `docker-compose.yml` to point, temporarily, to this new local image.

It should be something like this. You can do this on the same system you're running Teslamate. Make sure you don't have already a `teslamate` directory because the first command will create one.

```
git clone https://github.com/jsight/teslamate.git
cd teslamate
git reset --hard 8134150b247eec5a08572e62fdc4ebe6fda22f63
git clean -df
docker build . -t teslamate-patch
```

If all commands are successful, then you can just point your `docker-compose.yml` to your local patched image.

```
services:
  teslamate:
    image: teslamate-patch
```

Another option is to clone the official repository, then apply manually the change, then build the image in the same way. It should be the same.

**Comment by SebastianGode** [comment]
I guess once @adriankumpf gets his car updated to the 2023.38.x this PR will get merged.
So shouldn't take that much longer again although I personally would suggest Adrian to add a second trsutworthy maintainer to the repo :)

**Comment by tpd-opitz** [comment]
> If all commands are successful, then you can just point your docker-compose.yml to your local patched image.
> 
> services:
>   teslamate:
>    image: teslamate-patch

Is `teslamate-patch` just an identifier I need to use at both places, the `docker build` command and the `docker-compose.yml`  or are there any constraints to the directories involved?

**Comment by sargue** [comment]
Correct, it's just a tag, any string will do. As you point out, you just need to make sure it's the same on the docker build command and the `docker-compose.yml`.

There's no restriction on where you build or use the image, it's all a reference in the docker local repository. You can see that with `docker image ls`.

By the way, I've been told that grafana needs to be updated as well, as the current `master` branch of teslamate has some changes as well.

If someone tries it, please share the outcome here.

**Comment by tpd-opitz** [comment]
> ```
> git clone https://github.com/jsight/teslamate.git
> cd teslamate
> git reset --hard 8134150b247eec5a08572e62fdc4ebe6fda22f63
> git clean -df
> docker build . -t teslamate-patch
> ```
> 
> If all commands are successful, then you can just point your `docker-compose.yml` to your local patched image.
> 
> ```
> services:
>   teslamate:
>     image: teslamate-patch
> ```

I did that:
```

~/teslamate$ git clone https://github.com/jsight/teslamate.git geo-location-fix/
~/teslamate$ git -C geo-location-fix/ reset --hard 8134150b247eec5a08572e62fdc4ebe6fda22f63
~/teslamate$ docker build geo-location-fix/ -t teslamate-patch
Successfully built e2b76d9e7720
Successfully tagged teslamate-patch:latest
~/teslamate$ head -7 docker-compose.yml 
version: "3"

services:
  teslamate:
    # image: teslamate/teslamate:latest
    image: teslamate-patch:latest
    restart: always
~/teslamate$ docker-compose pull
Pulling teslamate ... error
Pulling database  ... done
Pulling grafana   ... done
Pulling mosquitto ... done

ERROR: for teslamate  pull access denied for teslamate-patch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: pull access denied for teslamate-patch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
Do I have a misconfiguration of docker?

**Comment by sargue** [comment]
@tpd-opitz , remove the `:latest` from the image line on the `docker-compose.yml`. It's trying to pull the image from a remote repository, but there's no remote repository (the image is local).

**Comment by rickou** [comment]
> Change has been pushed to docker here: https://hub.docker.com/repository/docker/jsightler/teslamate/general
> 
> Also updated to (hopefully) be backward compatible and less crashy. :)

Hi @jsight,
so, as everybody, i just updated my TMY to 2023.38.6 (from 2023.32.9) and teslamate stops working.

I run teslamate on my raspberry (without docker)
I use your latest patch version (endpoint update) to patch it and rebuild it
But i get errors when running and no more data are displayed on the root website, neither on grafana overview displaying car "offline"

I reverted to the previous patch version, and now all seems to works fine. (at least since few minutes)

i think the error was:
`Nov 10 20:42:49 raspberrypi teslamate[28865]: 2023-11-10 20:42:49.451 [error] GenStateMachine :"1" terminating
Nov 10 20:42:49 raspberrypi teslamate[28865]: ** (MatchError) no match of right hand side value: {:error, #Ecto.Changeset<action: :insert, changes: %{battery_heater: false, battery_heater_on: false, battery_level: 42, date: ~U[2023-11-10 19:42:49.351000Z], driver_temp_setting: Decimal.new("21.0"), est_battery_range_km: Decimal.new("131.48"), fan_status: 0, ideal_battery_range_km: Decimal.new("170.8"), inside_temp: Decimal.new("8.2"), is_climate_on: false, is_front_defroster_on: false, is_rear_defroster_on: false, odometer: 9329.662442, outside_temp: Decimal.new("7.0"), passenger_temp_setting: Decimal.new("21.0"), power: 0, rated_battery_range_km: Decimal.new("170.8"), tpms_pressure_fl: Decimal.new("2.65"), tpms_pressure_fr: Decimal.new("2.7"), tpms_pressure_rl: Decimal.new("2.725"), tpms_pressure_rr: Decimal.new("2.7"), usable_battery_level: 41}, errors: [latitude: {"can't be blank", [validation: :required]}, longitude: {"can't be blank", [validation: :required]}], data: #TeslaMate.Log.Position<>, valid?: false>}
Nov 10 20:42:49 raspberrypi teslamate[28865]:     (teslamate 1.27.3) lib/teslamate/vehicles/vehicle.ex:721: anonymous fn/4 in TeslaMate.Vehicles.Vehicle.handle_event/4
Nov 10 20:42:49 raspberrypi teslamate[28865]:     (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
Nov 10 20:42:49 raspberrypi teslamate[28865]:     (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
Nov 10 20:42:49 raspberrypi teslamate[28865]:     (teslamate 1.27.3) lib/teslamate/vehicles/vehicle.ex:713: TeslaMate.Vehicles.Vehicle.handle_event/4
Nov 10 20:42:49 raspberrypi teslamate[28865]:     (stdlib 3.14) gen_statem.erl:1168: :gen_statem.loop_state_callback/11
Nov 10 20:42:49 raspberrypi teslamate[28865]:     (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
`

**Review by brianmay — APPROVED** [review]

**Comment by brianmay** [comment]
Big question is: Is this change permanent? Or is Tesla going to change in the future and break this yet again?

**Comment by jaymunro** [comment]
Is there some way to up the priority on this? TeslaMate is completely broken with the the new API from Tesla.

**Comment by nelsongraca** [comment]
any timeline to merge this?

**Comment by jsight** [comment]
@brianmay It is in the official API documentation. They could change it further, but I'd guess they will document any further changes as well.

**Comment by brianmay** [comment]
There is official API documentation? Where is this? Everything I have seen clearly says unofficial only.

**Comment by jsight** [comment]
@brianmay Official API docs: https://developer.tesla.com/docs/fleet-api#vehicle_data

It is listed as the "fleet API", but the ones that I've seen are the same ones that we are used to. The notes call out the specific changes in 2023.38+ as well.

**Comment by swiffer** [comment]
Fact is that the current latest version 1.27.3 is broken and the fix discussed here is working well (and is documented change for the fleet API). Not having this or #3398 merged means broken Teslamate. There are more and more forks popping up

- https://github.com/MyTeslaMate/teslamate
- https://github.com/teslamate-fork/teslamate-fork

In addition there are efforts of coordinating a fork

- https://github.com/adriankumpf/teslamate/discussions/3396
- https://github.com/adriankumpf/teslamate/discussions/3384
- https://github.com/adriankumpf/teslamate/issues/3399

It would be really great to avoid that, broden the admin and combine forces in making teslamate a better product - or at least try to coordinate forking.

**Comment by brianmay** [comment]
I have had to use my fork for some time, simply because I have not had any feedback on my pr #3087. This in turn reduces motivation to work on other issues that have been nagging me.

I can understand though that @adriankumpf may feel that he is unable to keep with with this project anymore. I have been in this situation myself on a number of occasions.

I think we are all very grateful for the time and effort that @adriankumpf and others have spent on this project to date.

Handing over the project is a big step too, can you really trust the new maintainer? I have heard some horror stories where this can go wrong. In at least one case the new maintainer inserted malicious code into a project he had just taken over. And plenty of times where I accidentally end up being the new maintainer, and I am already over committed.

The problem with creating a fork, is that 50 forks is not going to help. We need one fork that the entire community can get behind and support. Maybe one, like the above that isn't directly tied to one person, so that the responsible people can change with time too.

If we can agree on one fork to be the new official repo, we can then ask github to mark it as such. Then the annotations will change to make this project an fork of the new official fork, rather then vice verse.

**Comment by szinn** [comment]
I can confirm this API works on 2023.27.7 as well. The vehicle_data_combo likely isn't needed since it appears to be an encoded blob and doesn't add anything new to the remainder of the request.

**Comment by Dulanic** [comment]
With https://github.com/teslamate-org/teslamate/pull/3398 merged, this is is no longer needed correct?

**Comment by Dulanic** [comment]
> I have had to use my fork for some time, simply because I have not had any feedback on my pr #3087. This in turn reduces motivation to work on other issues that have been nagging me.
> 
> I can understand though that @adriankumpf may feel that he is unable to keep with with this project anymore. I have been in this situation myself on a number of occasions.
> 
> I think we are all very grateful for the time and effort that @adriankumpf and others have spent on this project to date.
> 
> Handing over the project is a big step too, can you really trust the new maintainer? I have heard some horror stories where this can go wrong. In at least one case the new maintainer inserted malicious code into a project he had just taken over. And plenty of times where I accidentally end up being the new maintainer, and I am already over committed.
> 
> The problem with creating a fork, is that 50 forks is not going to help. We need one fork that the entire community can get behind and support. Maybe one, like the above that isn't directly tied to one person, so that the responsible people can change with time too.
> 
> If we can agree on one fork to be the new official repo, we can then ask github to mark it as such. Then the annotations will change to make this project an fork of the new official fork, rather then vice verse.

I dont disagree, there needs to be a head person responsible for all of it. Who that can be? I'm not sure at this point. But I think we are open to talking about it. There is a open discussion currently.

**Pull request closed without merging**
