### PR TITLE
Update charges.json: Add cost/kWh

### PR DESCRIPTION
**Pull request by DrMichael**
Add cost per kWh per https://github.com/teslamate-org/teslamate/discussions/3536

### CODE REVIEW

**Comment by NirKli** [comment]
> Still learning: How would I request a review? I am puzzled: it is already in _egde_, but not in _latest_?

This is how to request a review. It will be included in the latest release once this PR (Pull Request) is merged. (Depends on the CI )

**Comment by JakobLichterfeld** [comment]
> It was added in [639f9cb](https://github.com/teslamate-org/teslamate/commit/639f9cba4e4e77d4fb009c3fae46fce05d8e2d4a) and somehow diappeared, what I cannot see in the history. Strange.

You can look into file history, latest change was your mentioned PR, see https://github.com/teslamate-org/teslamate/commits/639f9cba4e4e77d4fb009c3fae46fce05d8e2d4a/grafana/dashboards/charges.json

**Comment by JakobLichterfeld** [comment]
> Still learning: How would I request a review? Now it is neitther in _egde_ nor in _latest_ It was added in [639f9cb](https://github.com/teslamate-org/teslamate/commit/639f9cba4e4e77d4fb009c3fae46fce05d8e2d4a) and somehow diappeared, what I cannot see in the history. Strange.

https://docs.github.com/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review

**Comment by DrMichael** [comment]
> You can look into file history, latest change was your mentioned PR, see https://github.com/teslamate-org/teslamate/commits/639f9cba4e4e77d4fb009c3fae46fce05d8e2d4a/grafana/dashboards/charges.json
> 
> And the edits are in master:
> 
> https://github.com/teslamate-org/teslamate/blob/639f9cba4e4e77d4fb009c3fae46fce05d8e2d4a/grafana/dashboards/charges.json#L713

Yes, that is, what confuses me. It is in the latest history, it is in master, but it does not show up in edge nore in latest.

**Comment by DrMichael** [comment]
I found the issue. the calculation for cost/kWh is missing in the master version. So it does not appear in latest and edge.
I will make a new PR...

**Comment by DrMichael** [comment]
> @DrMichael you can test these changes with the dedicated grafana image: `ghcr.io/teslamate-org/teslamate/grafana:pr-3537` https://github.com/teslamate-org/teslamate/pkgs/container/teslamate%2Fgrafana/153840916?tag=pr-3537

Yes, got that. Great new feature! Thanks

**Pull request closed without merging**
