### PR TITLE
ci: use elixir 1.16

### PR DESCRIPTION
**Pull request by JakobLichterfeld**
Use Elixir 1.16 in CI to solve #3464

### CODE REVIEW

**Comment by DrMichael** [comment]
Would that fix the failed checks?
@JakobLichterfeld you can also merge...

**Comment by JakobLichterfeld** [comment]
@DrMichael please stop merging, we can test CI without merging.
Merging unreviewed and untested stuff is bad repository sanity.

**Comment by DrMichael** [comment]
> @DrMichael please stop merging, we can test CI without merging. Merging unreviewed and untested stuff is bad repository sanity.

Will refrain from merging that stuff. How do you test?

**Comment by JakobLichterfeld** [comment]
You can see the CI test for each PR under checks, for example https://github.com/teslamate-org/teslamate/pull/3465/checks

So it is sort of first layer of review: does the new Pull Request break any predefined test or not. If it passes, than we start to review further.

**Pull request merged**
