### PR TITLE
ci: pin github action dependencies to protect against supply chain attacks

### PR DESCRIPTION
**Pull request by JakobLichterfeld**

### CODE REVIEW

**Comment by parkr** [comment]
Was there recently an attack on any of these actions? What prompted this?

**Comment by JakobLichterfeld** [comment]
As we encountered attacks via malicious commits before this is an additional precautionary measure. Supply chain attacks are a more common thing these days and pinning dependencies by commit rather than release (which can be overwritten) is state of the art sec.

**Comment by parkr** [comment]
Ok! Note that if a malicious user creates a branch with the given sha you've chosen here, you'll get that branch instead of SHA. So this doesn't make you immune, it just makes the work harder for an attacker. https://security.stackexchange.com/a/233268

**Comment by brianmay** [comment]
I think github tries to protect against this also.

```
at 09:36:35 ❯ git clone git@github.com:brianmay/ambiguous.git
Cloning into 'ambiguous'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (5/5), 12.84 KiB | 48.00 KiB/s, done.

at 09:36:56 ❯ git show
fatal: not a git repository (or any of the parent directories): .git

at 09:36:58 ❌128 ❯ cd ambiguous

at 09:37:01 ❯ git show

at 09:37:05 ❯ git checkout -b 82447f0b16dc784e734dfbeb9d6eae35912bfb62
Switched to a new branch '82447f0b16dc784e734dfbeb9d6eae35912bfb62'

at 09:37:14 ❯ git commit
On branch 82447f0b16dc784e734dfbeb9d6eae35912bfb62
nothing to commit, working tree clean

at 09:37:16 ❌1 ❯ vim README.md

at 09:37:27 ❯ git add -p
diff --git a/README.md b/README.md
index bc4f7e8..5ca6d68 100644
--- a/README.md
+++ b/README.md
@@ -1 +1,3 @@
-# ambiguous
\ No newline at end of file
+# ambiguous
+
+Changes to branch 82447f0b16dc784e734dfbeb9d6eae35912bfb62.
(1/1) Stage this hunk [y,n,q,a,d,e,?]? y

at 09:37:30 ❯ git commit
[82447f0b16dc784e734dfbeb9d6eae35912bfb62 c1ee56e] Changes to branch 82447f0b16dc784e734dfbeb9d6eae35912bfb62
 1 file changed, 3 insertions(+), 1 deletion(-)

at 09:37:40 ❯ git push
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 20 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 336 bytes | 336.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote: error: GH002: Sorry, branch or tag names consisting of 40 hex characters are not allowed.
remote: error: Invalid branch or tag name "82447f0b16dc784e734dfbeb9d6eae35912bfb62"
To github.com:brianmay/ambiguous.git
 ! [remote rejected] 82447f0b16dc784e734dfbeb9d6eae35912bfb62 -> 82447f0b16dc784e734dfbeb9d6eae35912bfb62 (pre-receive hook declined)
error: failed to push some refs to 'github.com:brianmay/ambiguous.git'
```

**Comment by JakobLichterfeld** [comment]
> So this doesn't make you immune, it just makes the work harder for an attacker.

As always in sec, there is no immune. 

> I think github tries to protect against this also.

This is my understanding as well. Github verifies that it is a commit and not a branch name, so this is indeed a strong security measure, which is why I decided to implement it.

**Comment by parkr** [comment]
```
remote: error: GH002: Sorry, branch or tag names consisting of 40 hex characters are not allowed.
```

Very cool, I did not know about this! Seems all is well then. 👍

**Comment by JakobLichterfeld** [comment]
> Very cool, I did not know about this! Seems all is well then. 👍

That's why I pinned with full commit hash :-)

**Pull request merged**
