### PR TITLE
feat: add Detailed Energy Use to drive-details

### LINKED ISSUE #4375: [Feature] Add total kWh Used/ recovered due to regenerative braking to drive details
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I would love to see a feature where it would be calculated how much energy in kWh was used or recovered by regenerative braking in total for a single drive. 

I know the drive details already show an "Energy Used" but this is rather a combination from both.

So if the car used 20 kWh for the drive and recovered 10 kWh by regenerative braking it would show 10 kWh Energy Used.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Relevant log output

```shell
-
```

### Screenshots

_No response_

### Additional data

_No response_

### Type of installation

Docker

### Version

v1.31.1

### PR DESCRIPTION
**Pull request by jameskitt616**
Add Detailed Energy Use to Drive Details to fix #4375.
image

@swiffer [ping ](https://github.com/teslamate-org/teslamate/issues/4375#issuecomment-2472824891)

### CODE REVIEW

**Comment by swiffer** [comment]
Thanks for opening this PR - I do prefer getting #4367 in first.

This PR seems to be based on Grafana build bundled with TeslaMate v1.31.1, exports should be done on top of the latest master to avoid overwriting other changes / reduce noise from changed Grafana schema version.

To the added stats - as numbers are not fully matching and 10.6 kwh & 12.4 kwh are both referred to as "used" I would prefer changing that to Energy recovered. As the metric is new I've added a small explanation as well.

grafik

https://github.com/teslamate-org/teslamate/commit/371c83adca43c0a84d1a1aa194c2551e6b26bf59

**Comment by jameskitt616** [comment]
I copied your Updated file into the PR now.

**Comment by cschanzle** [comment]
Blease use "braking" instead of "breaking".

**Comment by swiffer** [comment]
@jameskitt616  - could you reset this branch to lastest master and include commit f71c965fb1b97152ce607249bb871f7742b24277

(already including the change from "breaking" to "braking").

**Comment by jameskitt616** [comment]
Resolved the conflicts

**Comment by swiffer** [comment]
Thank you, would have been better to do a rebase instead to keep commits history clean but i think @JakobLichterfeld will do a squash merge anyhow.

**Comment by JakobLichterfeld** [comment]
> but i think @JakobLichterfeld will do a squash merge anyhow.

In most cases yes. In #4367 it was by mistake.

**Comment by swiffer** [comment]
ready for merge with squash

**Review by JakobLichterfeld — APPROVED** [review]
lgtm, performance: instant on slow hw

**Pull request merged**
