### PR TITLE
WIP: Update VERSION to test CI

### PR DESCRIPTION
**Pull request by jlestel**
Test PR to demonstrate how CI build images (hosted on GHCR) from PR sources.

### CODE REVIEW

**Review by JakobLichterfeld — APPROVED** [review]

**Comment by JakobLichterfeld** [comment]
I think about releasing new version the next days. Would go with 1.28.0 to show the first release of teslamate-org.

**Comment by jlestel** [comment]
> I think about releasing new version the next days. Would go with 1.28.0 to show the first release of teslamate-org.

It was just a test PR to trigger the CI :) the result seems correct.

To finalize, we need to make the packages https://github.com/teslamate/teslamate/pkgs/container/teslamate and https://github.com/teslamate/teslamate/pkgs/container/teslamate%2Fgrafana public

**Comment by JakobLichterfeld** [comment]
> It was just a test PR to trigger the CI :) the result seems correct.

I know, just wanna give you a heads up :-)

Why is the digest size 0 byte?

**Comment by jlestel** [comment]
@JakobLichterfeld in order not to trigger the CI on each PR, do you want to condition its launch on the presence of a particular label?

**Comment by jlestel** [comment]
> Why is the digest size 0 byte?

I guess it's because it only contains 3 empty files. an approximation of GH, that's 643 bytes in reality

**Comment by DrMichael** [comment]
> I think about releasing new version the next days. Would go with 1.28.0 to show the first release of teslamate-org.

That wouls be 'latest', right? What about 'edge'? When and how often is that being updated?

**Comment by jlestel** [comment]
> Edit: I do not have access to the pkgs

@adriankumpf @DrMichael could you make packages public? I want to give access to the intermediate build to facilitate the testing of certain PRs.

The 2 packages: 
- https://github.com/teslamate/teslamate/pkgs/container/teslamate
- https://github.com/teslamate/teslamate/pkgs/container/teslamate%2Fgrafana

**Comment by jlestel** [comment]
> > I think about releasing new version the next days. Would go with 1.28.0 to show the first release of teslamate-org.
> 
> That wouls be 'latest', right? What about 'edge'? When and how often is that being updated?

- Edge is released each sunday at 03:00 AM and based on master
- Latest is released with a version (v*.*.*)

**Comment by DrMichael** [comment]
> @adriankumpf @DrMichael could you make packages public? I want to give access to the intermediate build to facilitate the testing of certain PRs.
> 
> The 2 packages:
> 
> * https://github.com/teslamate/teslamate/pkgs/container/teslamate
> * https://github.com/teslamate/teslamate/pkgs/container/teslamate%2Fgrafana

I get a 404 with those links...

**Comment by jlestel** [comment]
> I get a 404 with those links...

You don't have access because it's not public yet. I think only Adrian can give us access to it :)

**Comment by JakobLichterfeld** [comment]
> in order not to trigger the CI on each PR, do you want to condition its launch on the presence of a particular label?

For now, we can go with all PR without `.github` (as we do right now) imo, since tagging is a manual process. We can exclude doc changes, but I would stick with all for now.

**Comment by jlestel** [comment]
> https://github.com/orgs/teslamate-org/packages/container/package/teslamate
> https://github.com/orgs/teslamate-org/packages/container/package/teslamate%2Fgrafana

Sorry, this is the good links. 404 for me because not public.

**Comment by JakobLichterfeld** [comment]
Yeah, these links are working, I could not change permissions, perhaps @DrMichael can

**Comment by DrMichael** [comment]
Sorry, no. @adriankumpf has to do that.
image

**Comment by jlestel** [comment]
> Sorry, no. @adriankumpf has to do that. image

@DrMichael do you have a way to contact @adriankumpf about this?

**Comment by DrMichael** [comment]
No, only this way. Sorry.
@adriankumpf It might be good to make @JakobLichterfeld and/or @jlestel admin of teslamate-org.

**Comment by adriankumpf** [comment]
@DrMichael I have changed an org setting that I believe should allow members to make packages public. Both packages are now also public

**Comment by DrMichael** [comment]
> * Edge is released each sunday at 03:00 AM and based on master

Are you sure. At least the Charges dashboard in edge is still  the old one. In latest, it is the new one.

**Comment by JakobLichterfeld** [comment]
https://github.com/teslamate-org/teslamate/blob/7329b2bf3aa23aea3f434cd56fb329bac3eaf081/.github/workflows/buildx.yml#L6

**Comment by DrMichael** [comment]
Hmmm, strange. Pulled fresh grafana:edge...
Still in Charges the rightmost is Driven with edge, Odometer with latest.

**Pull request merged**
