### PR TITLE
Add charging_state to VehicleSummary

### PR DESCRIPTION
**Pull request by brianmay**
Fixes: #3078

This will publish the state to MQTT and allow sensing of the `NoPower` state.

### CODE REVIEW

**Comment by brianmay** [comment]
Notes:

1. Not tested yet. About to do that.
2. Wondering if I should add to `@always_published` which will publish `nil` values. But most likely reason for nil value is because `vehicle.charge_state` is `nil`, which means we don't know this value just yet, which means we shouldn't publish.

Actually thinking we shouldn't publish any `vehicle.charge_state` values if that value is `nil`, because it does mean we don't know what the value is. But fixing this beyond the scope of this simple pull request.

**Comment by brianmay** [comment]
As far as I can tell the CI test failures are unrelated.

**Comment by brianmay** [comment]
Preliminary testing seems to indicate it is working...

**Comment by JakobLichterfeld** [comment]
> 1. Not tested yet. About to do that.

Did you test it in the meantime?

**Comment by brianmay** [comment]
Yes, is tested and working. I see there is a conflict, will try to resolve that.

**Comment by brianmay** [comment]
I rebased this against the latest master.

**Comment by brianmay** [comment]
I think the test cases are not connected to this PR.

**Review by JakobLichterfeld — APPROVED** [review]
lgtm, failed CI is handled in #3428

**Pull request merged**
