### PR TITLE
fix: Charges Dashboard -> Range added renamed to Ø Charge rate

### LINKED ISSUE #4348: "Range Added" has incorrect units on the Charges dashboard
> Hello, I'm a new user in this exact issue is something that bothered me enough to come here and search for answers. Was this issue corrected yet? I'm see the same behavior as op. 
> 
> In the "range added" column, I would expect to see the number of miles that I gained during the charging session. Instead, it shows me how _fast_ the charging occurred. This is super misleading because if I charged for 28 min and gained 20 miles of range, it displays 45 mph. If I was charged for exactly one hour, then that value would be accurate but I'd argue that most people are not charging for exactly one hour, and would rather see the number of miles worth of change during the amount of time they were plugged in and not for one hour. 
> 
> Can this please be corrected or can there be an option to display the actual range added?

_Originally posted by @1920x1200 in https://github.com/teslamate-org/teslamate/issues/4087#issuecomment-2453285969_

### PR DESCRIPTION
**Pull request by swiffer**
fixes #4348 (should be merged on top of #4338, I can rebase after merge)

### CODE REVIEW

**Comment by JakobLichterfeld** [comment]
hm seams like you used your #4338 branch for this pr

**Comment by swiffer** [comment]
yes 👍

**Comment by JakobLichterfeld** [comment]
@swiffer any idea why it still shows 27 changes after merging #4338 ?

**Review by JakobLichterfeld — APPROVED** [review]
perfect, ty.

**Comment by JakobLichterfeld** [comment]
Tested successfully.

**Pull request merged**
