### PR TITLE
feat: add LFP Battery setting for car settings

### PR DESCRIPTION
**Pull request by cwanja**
**Disclosure** this is not complete in anyway. This adds the settings and updates the webpage. I created this PR based upon https://github.com/teslamate-org/teslamate/commit/a413e8ce2cabf6c1eb024d88c0c87a957f45c241 from @adriankumpf and my work on #2727. 

What is **missing** is:
1. Dashboards. @swiffer mentioned he would work on those
2. All the updates to "LC_Messages" - no clue what these are 🤷🏼 

Do your worst! 

Edit: moving to "completed" from my original post:
**Completed after original push**
1. Migration scripts - Can someone validate this? Based it upon a457d17 where the `streaming api` setting was created. 
2. Test scripts - attempted in 7604d17 (Edit: and then many more 😄 but got it working! 🥳 ).

### CODE REVIEW

**Comment by cwanja** [comment]
Since we are just creating a toggle, does Tesla have any documentation we can link to for a user to check if their car is an LFP battery or not?

**Comment by cwanja** [comment]
@mark3-dev - really dumb question. But what updates do I need to do to the `default.pot` files? It looks like random numbers are added to the end of lines. Mimicking your PR #3993

**Comment by mark3-dev** [comment]
> @mark3-dev - really dumb question. But what updates do I need to do to the `default.pot` files? It looks like random numbers are added to the end of lines. Mimicking your PR #3993

@cwanja Those numbers are the line numbers of where the gettext translations are used. You can update the pot files by following this https://docs.teslamate.org/docs/development#update-pot-files-extract-messages-for-translation

**Comment by cwanja** [comment]
> > @mark3-dev - really dumb question. But what updates do I need to do to the `default.pot` files? It looks like random numbers are added to the end of lines. Mimicking your PR #3993
> 
> @cwanja Those numbers are the line numbers of where the gettext translations are used. You can update the pot files by following this https://docs.teslamate.org/docs/development#update-pot-files-extract-messages-for-translation

Thanks @mark3-dev. Feel like I know the answer here, but will ask anyways. Is there any way execute this from the GUI in the branch? Might be crazy to say, but I have modified the code in GitHub UI. I do not have a local repo or anything.

**Comment by mark3-dev** [comment]
> > > @mark3-dev - really dumb question. But what updates do I need to do to the `default.pot` files? It looks like random numbers are added to the end of lines. Mimicking your PR #3993
> > 
> > 
> > @cwanja Those numbers are the line numbers of where the gettext translations are used. You can update the pot files by following this https://docs.teslamate.org/docs/development#update-pot-files-extract-messages-for-translation
> 
> Thanks @mark3-dev. Feel like I know the answer here, but will ask anyways. Is there any way execute this from the GUI in the branch? Might be crazy to say, but I have modified the code in GitHub UI. I do not have a local repo or anything.

@cwanja I'm not sure if there is any other way to do it other than pulling down the files and running it.

**Comment by 07stuntar1** [comment]
Weird that all my datapoints are missing from the LFP battery after the last update. Anyway to see if it's still in the database? I dont believe its even plotting anymore.

**Comment by swiffer** [comment]
@07stuntar1 - as we've said - in terms of data there is no difference between LFP / non-LFP. The only difference that has been make back then was in terms of how the data is visualized. You seem to are operating on different databases.

**Comment by 07stuntar1** [comment]
> @07stuntar1 - as we've said - in terms of data there is no difference between LFP / non-LFP. The only difference that has been make back then was in terms of how the data is visualized. You seem to are operating on different databases.

How can I fix it? The rest of the pages data is fine. It’s just the battery page

**Comment by cwanja** [comment]
Raising my hand here - I am at a loss for running the pots update. I tried through VS code and GitHub codespaces. Could not get `mix` working. If there is a way to add a collaborator on this branch, please let me know. Otherwise, someone can open a new branch and use my changes as a baseline to get this added.

**Comment by cwanja** [comment]
Welp. I have no clue how I did it. But I did 🍾 

Can someone review and test? @JakobLichterfeld @swiffer

**Review by JakobLichterfeld — APPROVED** [review]
Awesome, lgtm

**Comment by JakobLichterfeld** [comment]
Successfully tested
- [x] Migration
- [x] Setting
- [ ] Dashboard

**Comment by swiffer** [comment]
Will take care of changing dashboards after merge!

**Comment by JakobLichterfeld** [comment]
Sorry, due to merging #3993, may I ask you to update the pot again? And merge the settings_test? Sorry for the inconvenience.

**Comment by JakobLichterfeld** [comment]
> Sorry, due to merging #3993, may I ask you to update the pot again? And merge the settings_test? Sorry for the inconvenience.

I try to solve it via a separate branch as I do not have write access to your repo.

**Pull request merged**
