### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by sakul1234**

### CODE REVIEW

**Comment by JakobLichterfeld** [comment]
@jlestel Why was this not prevented from running?

**Comment by JakobLichterfeld** [comment]
stop targeting

**Comment by jlestel** [comment]
> @jlestel Why was this not prevented from running?

Hi Jakob, I'm looking in more detail to find the right answer.

**Comment by jlestel** [comment]
Hum you're right, as mentioned in the GH workflow docs: [You should not use path filtering to skip workflow runs if the workflow has been configured to be required...](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#example-including-paths)

I'm thinking of using this module to really condition the execution of the workflow: https://github.com/dorny/paths-filter

Let me know what you think before I implement it.

**Comment by JakobLichterfeld** [comment]
Lets track it in #3559

**Pull request closed without merging**
