### PR TITLE
Fix Axis Labels for XY Chart in Battery Health and reduces Query count in Visited

### LINKED ISSUE #4353: Show full VIN in dashboards when no car-name set at all
Hi everyone, 

I had previously opened this pull request, for cases of unnamed vehicles
* https://github.com/teslamate-org/teslamate/pull/4198

Looks like the behavior changed in this pull request 

### To:

In my opinion, displaying a bunch of numbers with no context isn't too great. 

Would you be opposed if I opened a new pull request to change back the case of unnamed vehicles to `VIN $full_vin`?

In summary:
* Uniquely named vehicles: `$Name`
* Duplicate named vehicles: `$Name - $Last_six_of_vin`
* Unnamed vehicles: `VIN $Full_vin`

c.c. @swiffer , @JakobLichterfeld , @edgararroyo

_Originally posted by @arcastro in https://github.com/teslamate-org/teslamate/issues/4230#issuecomment-2453862453_

### LINKED ISSUE #4358: Charge details: Missing Axis labels in Charging Curve
Charge details:

v1.31.1: 
image

this pr: 
image

--> no label on x-axis anymore, diagram shifted

_Originally posted by @JakobLichterfeld in https://github.com/teslamate-org/teslamate/issues/4338#issuecomment-2453341052_

### PR DESCRIPTION
**Pull request by swiffer**
fixes #4358 - I haven't found a way to change the min/max for X Axis only - so for now that stays as it is.
fixes #4353 - Show full VIN when no name is set

### CODE REVIEW

**Comment by swiffer** [comment]
@JakobLichterfeld lgtm, will open a follow up PR for more consistent naming of columns afterwards (~ tommorow).

**Comment by swiffer** [comment]
Draft!

**Comment by swiffer** [comment]
@JakobLichterfeld - ready, lgtm (i'm planning to address #4268 and #4350 in an upcoming PR (most likely tomorrow)). would be great to cut a release afterwards.

**Review by JakobLichterfeld — APPROVED** [review]
Thank you.
LGTM.

#4358: tested successfully
#4353: not tested on my end

**Pull request merged**
