### PR TITLE
Improve estimations on Battery Health dashboard

### PR DESCRIPTION
**Pull request by jheredianet**
These are some fixes and improvements on Battery Health dashboard:

- Improve performance on most queries, avoid using CTEs instead of subqueries. 
- Fine tuning of queries in order to get more accurate estimations
- Minor fixes, rearrange and more information on stats (hints and labels)

image

### CODE REVIEW

**Review by JakobLichterfeld — APPROVED** [review]
lgtm, ty!

**Comment by darvintang** [comment]
刚刚我把TeslaMate升级到1.28.5，发现我的车MaxCapacity值变成了84.6，CurrentCapacity值变成了83.1，而我的车官方数据是78.4度，CurrentRange数据也根车机上显示的不一样了。根据我从数据库数据观察到CurrentCapacity的计算好像变成了charge_energy_used/(end_battery_level-start_battery_level)，这是不合理的，charge_energy_used是消耗的电量，车上的空调等电器在充电过程中消耗的是没有充入电池的，所以该算法是不合理的。

**Comment by kkthxbye-code** [comment]
This seems less accurate than the old, at least for my car.

Comparing the Battery Health - LFP (wasn't updated in this PR, that is another issue) and the new one:

Old:

```
Usable (new)
61.1 kWh
Usable (now)
58.3 kWh
Difference
-2.8 kWh 
```

This is a 2023 RWD model 3, which should have a usable capacity of around 57.5 kwh and 60 kwh total.

New:

```
Usable (new)
63.0 kWh
Usable (now)
61.0 kWh
Difference
-2.0 kWh
```

**Comment by kkthxbye-code** [comment]
> Did you test this PR image? The PR is not included in v1.28.5 only in edge version

I'm on 1.28.5 and it is included in that image. Its included in the release notes for v1.28.5:

> Improve estimations on Battery Health dashboard (https://github.com/teslamate-org/teslamate/pull/3756 - @jheredianet)

I verified the json for the dashboard, and it is the updated version.

**Comment by JakobLichterfeld** [comment]
Sorry my bad, there has been a lot of updates related to this dashboard in the past.

**Pull request merged**
