### PR TITLE
Documentation for new endpoint changes

### PR DESCRIPTION
**Pull request by jlestel**
Add documentation the new endpoints as asked in #3959

### CODE REVIEW

**Comment by zlymeda** [comment]
If using self-hosted HTTP proxy, doesn't the token refresh also need `client_id`? https://developer.tesla.com/docs/fleet-api#third-party-token

**Comment by jlestel** [comment]
> If using self-hosted HTTP proxy, doesn't the token refresh also need `client_id`? https://developer.tesla.com/docs/fleet-api#third-party-token

You're right, I tried it and it works now with this PR #3984.

Check updates on doc on [the direct Tesla API part](https://deploy-preview-3978--teslamate.netlify.app/docs/guides/api#tesla-fleet-api).

**Review by JakobLichterfeld — APPROVED** [review]
Ty!
I hesitated at first because the reference to external projects for Fleet API use is not necessarily complete.

**Comment by jlestel** [comment]
Thank you

**Pull request merged**
