### PR TITLE
Timeline: fix kWh values and column layout for miles (#3846)

### PR DESCRIPTION
**Pull request by sdwalker**
Add the kWh multiplication needed for driving and parking when using miles
Use the same index value for the Range Diff column so the layout is the same with miles or kilometers

### CODE REVIEW

**Comment by DrMichael** [comment]
May I propose to use convert_km instead of CASE in the SQL statement? Just to be consistent.

**Comment by sdwalker** [comment]
> May I propose to use convert_km instead of CASE in the SQL statement? Just to be consistent.

convert_km divides by 1.60934 so the proper fix for charging looks to be to not use convert_km at all

From
convert_km((end_[[preferred_range]]_range_km - start_[[preferred_range]]_range_km)::NUMERIC, '$length_unit') * efficiency AS "kWh",
To
(end_[[preferred_range]]_range_km - start_[[preferred_range]]_range_km)::NUMERIC * efficiency AS "kWh",

Still looking at how to fix the parking query
convert_km(((LEAD(d.start_[[preferred_range]]_range_km) over w + (LEAD(d.start_km) over w - d.end_km)) - d.end_[[preferred_range]]_range_km)::NUMERIC, '$length_unit') * efficiency AS "kWh",

**Comment by JakobLichterfeld** [comment]
> Still looking at how to fix the parking query

Are you planning a separate PR or include in this one?

**Comment by sdwalker** [comment]
Can we assume the parking query is correct for metric users?
If so, a metric user would be able to remove the convert_km from the parking query, switch their units and confirm the unit conversion matches

**Comment by swiffer** [comment]
efficiency is stored as kwh/km, therefore convert_km seems not to be needed at all in these calculations, agree.

@dyxyl - do you want to update your PR based on latest master or should I open a follow up PR ?

**Review by swiffer — CHANGES_REQUESTED** [review]
efficiency is stored as kwh/km, therefore convert_km seems not to be needed at all in these calculations, agree.

@dyxyl - do you want to update your PR based on latest master or should I open a follow up PR ?

**Comment by dyxyl** [comment]
I don't have a PR for this -- it was @sdwalker who originated it.

**Comment by swiffer** [comment]
😆 - sorry. @sdwalker, would you like to update the PR ?

**Comment by swiffer** [comment]
with #4367 merged this one can be closed @JakobLichterfeld

**Pull request closed without merging**
