### PR TITLE
Velocity/Speed histogram in drive details dashboard

### PR DESCRIPTION
**Pull request by jheredianet**
Here is the adaptation to the change that has been suggested here https://github.com/teslamate-org/teslamate/issues/3835

Please, I would like, before doing a merge, for someone to manually import this dashboard into their test environment to see if any information or improvements are missing.

image

### CODE REVIEW

**Comment by JakobLichterfeld** [comment]
Test with

```
grafana:
       # image: teslamate/grafana:latest
      image: ghcr.io/teslamate-org/teslamate/grafana:pr-3836
```

**Comment by JakobLichterfeld** [comment]
Thank you!

Looks nearly perfect!

Minor changes:
- I would prefer if the Speed Histogram goes from 0 from the left to max on the right
- I would remove the unit on every x axis point
- I would add percentage above the bars

**Comment by jheredianet** [comment]
> Minor changes:
> 
> * I would prefer if the Speed Histogram goes from 0 from the left to max on the right
> * I would remove the unit on every x axis point
> * I would add percentage above the bars (or both, Minutes and percentage)

Ok, I will do the updates suggested. Need a little extra time.

**Comment by jheredianet** [comment]
> Minor changes:
> 
> * I would prefer if the Speed Histogram goes from 0 from the left to max on the right
> * I would remove the unit on every x axis point
> * I would add percentage above the bars (or both, Minutes and percentage)

@JakobLichterfeld  What about now?

image

**Comment by JakobLichterfeld** [comment]
Nearly perfect.
image

If there are lots of different speeds, the x-axis got a bit messy, therefore
> * I would remove the unit on every x axis point

image

**Comment by jheredianet** [comment]
> Remove the unit on every x axis point

What about now? I hope this one to be the perfect one ;-)

image

**Comment by sdwalker** [comment]
Missing units for the speed (an existing issue) but looks good otherwise
mi
image
km
image

Standardize the letter casing for all of the text?
Battery heater -> mixed casing
front left -> lower casing
Outside Temperature -> upper casing

**Comment by jheredianet** [comment]
> Standardize the letter casing

HI, I took the opportunity to consider your suggestions as well using upper casing

**Comment by JakobLichterfeld** [comment]
Awesome, ty!
image

**Comment by tjhart** [comment]
@jheredianet 

As I looked at this PR with regard to #3763, I noticed that the `speed` scale in the Drive panel now extends into the negative range. Is that realistic? Would that data set ever extend below zero? If not, why are we limiting that data to half of the vertical space in the graph? Are there other data sets in that graph that are now constrained to the top half of the graph with this change?

**Comment by cwanja** [comment]
@JakobLichterfeld (or anyone for that matter) what is the syntax to update your YML to pull a specific PR? I forget.

Is it:`image: teslamate/teslamate:pr-####`? This would be `image: teslamate/teslamate:pr-3836`.

**Comment by jheredianet** [comment]
> @jheredianet
> 
> As I looked at this PR with regard to #3763, I noticed that the `speed` scale in the Drive panel now extends into the negative range. Is that realistic? Would that data set ever extend below zero? If not, why are we limiting that data to half of the vertical space in the graph? Are there other data sets in that graph that are now constrained to the top half of the graph with this change?

Yes, as I've explained before, it's not only the speed that is represented in that axis. There are many metrics there. So, the challenge is if we adapt the axis for a specific metric, it would not be well represented for other one, like the Power which is the one that has positive and negative values (and even elevation perhaps). Maybe the Solomonic solution could be separating the familiar metrics in another graph (just as an idea)

**Comment by JakobLichterfeld** [comment]
> what is the syntax to update your YML to pull a specific PR? I forget.

```
grafana:
       # image: teslamate/grafana:latest
      image: ghcr.io/teslamate-org/teslamate/grafana:pr-3836
```

similar for TeslaMate image

**Comment by JakobLichterfeld** [comment]
> will update the contributing doc about this

done, see #3856

**Comment by cwanja** [comment]
Hate to say it, but with this PR the drive graph is completely useless for range in my opinion. The lines are all on top of each other.  Beyond speed and power, the lines mean nothing. I think we should roll this back @JakobLichterfeld @jheredianet.

This is the exact same drive from the screenshots in this comment https://github.com/teslamate-org/teslamate/issues/3763#issuecomment-2015943703
Screenshot 2024-04-17 at 8 27 58 PM

**Comment by jheredianet** [comment]
> Hate to say it, but with this PR the drive graph is completely useless for range in my opinion. The lines are all on top of each other. Beyond speed and power, the lines mean nothing. I think we should roll this back @JakobLichterfeld @jheredianet.

We return to the same thing that has already been mentioned before (at https://github.com/teslamate-org/teslamate/issues/3763#issuecomment-2058403045), in this panel the Y axis shows different units (speed per hour, power, range) and that is why it cannot fit for everything. From my point of view, I don't see a major problem about the ranges, beyond the fact that they are seen above the speed, the important thing for me is that both range lines show that there are no significant changes between them.

I don't think it's necessary to revert the PR, since there are other changes outside of this panel, on the contrary, I think we can try to improve it together. 

Maybe you could try to change is the "center cero" axis in this panel and then modify the Overwrite "Add Standard options > Min 0" you suggested to see if you get what you want. If so, a PR with those changes will be enough.

**Comment by JakobLichterfeld** [comment]
> Hate to say it, but with this PR the drive graph is completely useless for range in my opinion.

A reduce in range of 10 miles is so little, the graph is ok from my point of view.

**Comment by DrMichael** [comment]
Actually, I agree with @cwanja. But I think, the ranges and battery heater are not really relevant for a drive. Spee, SOC and Usable SOC might be the essential informations...
With ranges, batter heater:
image
Without (and centred_zero off):
image

**Comment by jheredianet** [comment]
> .... I think, the ranges and battery heater are not really relevant for a drive. Spee, SOC and Usable SOC might be the essential informations... 

I agree with @DrMichael for a drive is only important Speed, SOC, Power (and even elevation as a right Y axis) as I did in this dashboard https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards?tab=readme-ov-file#tracking-drives

image

That's why in a previous comment I've suggested as an idea, that maybe the Solomonic solution could be separating the familiar metrics in another graph (meaning Ranges and other metrics that do not interfere with units)

**Comment by cwanja** [comment]
> > Hate to say it, but with this PR the drive graph is completely useless for range in my opinion.
> 
> 
> 
> A reduce in range of 10 miles is so little, the graph is ok from my point of view.

@JakobLichterfeld I would agree that 10 miles is little range loss, however when comparing old and new graphs for the exact same drive it got worse from a readability standpoint. No more or less data is present on the new graph, it's just less readable and usable in my opinion.

**Comment by cwanja** [comment]
> Actually, turning off only centered zero makes it also a bit more comprehensible?
> 

I'd align with @DrMichael's third graph here. Would love to test it against the same drive.

**Comment by jheredianet** [comment]
> @jheredianet What is the rationale to have centered zero set to on?

It's because of the "Power" since it could be posistive and negative

**Comment by DrMichael** [comment]
But you don't need `centered zero` for that...

**Comment by jheredianet** [comment]
> But you don't need `centered zero` for that...

You're right, but having in mind that in this case I'm showing the elevation

With no "centered cero", the elevation seems that I'm traveling across a mountain (when in reality there is only a small variation around 100m)
image


With "centered cero" it looks better and elevation seems to be almost as an horizontal line (more accurate in reality and it is in tune with the power):
image

**Pull request merged**
