### PR TITLE
Update projects.md with new MMM

### PR DESCRIPTION
**Pull request by top-gun**
MMM-Teslamate has a new maintainer, updated the link to the new repo

### CODE REVIEW

**Review by JakobLichterfeld — APPROVED** [review]
thanks for your change!

**Comment by olexs** [comment]
This seems wrong. MMM-Teslamate and ha-addon-teslamate are separate projects with completely different goals and maintainers. MMM-Teslamate is still located where it always was. I think the wrong link has been changed here?

**Comment by JakobLichterfeld** [comment]
You are right, only checked the link on this one as there has been discussion about this and the PR was created out of this.
Thanks for spotting! Are you willing to correct with a new PR?

**Comment by olexs** [comment]
Yeah, I'll see if I can sort this out. Thanks!

**Pull request merged**
