### PR TITLE
fix: use product api endpoint to fetch vehicles

### PR DESCRIPTION
**Pull request by JakobLichterfeld**
#3629

### CODE REVIEW

**Comment by brianmay** [comment]
The concern I have with this is if you have other Tesla products, e.g. solar, they may get returned by the new API, and this could cause endless confusion if we try to process that as a car. If so, we might need some way of filtering the list returned so it only contains cars.

Unfortunately, not something I can test.

**Comment by JakobLichterfeld** [comment]
> The concern I have with this is if you have other Tesla products, e.g. solar, they may get returned by the new API, and this could cause endless confusion if we try to process that as a car. If so, we might need some way of filtering the list returned so it only contains cars.


100% that's why it's WIP, only wanted to test if we think in the right direction in general.

**Review by parkr — APPROVED** [review]

**Comment by weljajoh** [comment]
> > The concern I have with this is if you have other Tesla products, e.g. solar, they may get returned by the new API, and this could cause endless confusion if we try to process that as a car. If so, we might need some way of filtering the list returned so it only contains cars.
> 
> 100% that's why it's WIP, only wanted to test if we think in the right direction in general.

Testing for the presence of the vin and vehicle_id fields in the product_list response might be a good way to filter vehicles from the product list in the presence of powerwalls or solar. See the bottom part of https://github.com/tdorssers/TeslaPy/issues/156#issuecomment-1908246684

**Comment by lotharbach** [comment]
> Testing for the presence of the vin and vehicle_id fields in the product_list response might be a good way to filter vehicles from the product list in the presence of powerwalls or solar.

Agreed! I am somewhat sure the Tesla App checks primarily for "vehicle_id" to determine if a product from api/1/products should be tried to be loaded as a vehicle.

From decompiled apk, shortened for readability:

```
                        if (jSONObject != null && jSONObject.has("vehicle_id")) {
                            jSONObject.put("type", "VEHICLE");
                            Product fromJson = jx.a.f50357a.b().fromJson(jSONObject.toString());
                            arrayList.add((Vehicle) fromJson);
```

**Comment by brianmay** [comment]
I can't test this right now (I might have made syntax errors!), but I would imagine something like:

```diff
diff --git a/lib/tesla_api/vehicle.ex b/lib/tesla_api/vehicle.ex
index 9c25743d..59e2302c 100644
--- a/lib/tesla_api/vehicle.ex
+++ b/lib/tesla_api/vehicle.ex
@@ -30,7 +30,7 @@ defmodule TeslaApi.Vehicle do
       end

     TeslaApi.get(endpoint_url <> "/api/1/products", opts: [access_token: auth.token])
-    |> handle_response(transform: &result/1)
+    |> handle_response(transform: &list_result/1)
   end

   def get(%Auth{} = auth, id) do
@@ -61,6 +61,12 @@ defmodule TeslaApi.Vehicle do
     |> handle_response(transform: &result/1)
   end

+  def list_result(result) do
+    result
+    |> filter(fn(x) -> Map.has_key?(x, "vehicle_id"))
+    |> Enum.map(res, &result/1)
+  end
+
   def result(v) do
     %__MODULE__{
       id: v["id"],
@@ -88,7 +94,7 @@ defmodule TeslaApi.Vehicle do
     case env do
       %Tesla.Env{status: status, body: %{"response" => res}} when status in 200..299 ->
         transform = Keyword.get(opts, :transform, & &1)
-        {:ok, if(is_list(res), do: Enum.map(res, transform), else: transform.(res))}
+        {:ok, transform.(res)}

       %Tesla.Env{status: 401} = env ->
         {:error, %Error{reason: :unauthorized, env: env}}
```

This is a bit more invasive then I originally imagined, because originally the transform function was called for every element in the list, but this means we can't filter out list elements. So I changed the transform function to operate on the entire result. I think it should only get a list for the list API call, so this should be OK.

We could also do the filtering after the `handle_response` returns, but this is after we processed the result, which seems kind of yuck.

**Comment by brianmay** [comment]
As expected, are some dumb errors in above, will try to fix and test.

**Comment by brianmay** [comment]
It looks like this issue will only affect *new* installs, old installs will fall back to using the data from the database. But of course, this will be a problem if you have added/removed any vehicles.

```
Jan 26 09:47:34 iot2 teslamate[94614]: 2024-01-26 09:47:34.310 [warning] TeslaApi.Error / %{"error" => "Endpoint is only available on fleetapi. Visit https://developer.tesla.com/docs for more info", "error_description" => "", "response" => nil}
Jan 26 09:47:34 iot2 teslamate[94614]: 2024-01-26 09:47:34.310 [warning] Could not get vehicles: :unknown
Jan 26 09:47:34 iot2 teslamate[94614]: 2024-01-26 09:47:34.314 [warning] Using fallback vehicles:
Jan 26 09:47:34 iot2 teslamate[94614]:
Jan 26 09:47:34 iot2 teslamate[94614]: [
Jan 26 09:47:34 iot2 teslamate[94614]:   %TeslaApi.Vehicle{
Jan 26 09:47:34 iot2 teslamate[94614]:     id: <censored>,
Jan 26 09:47:34 iot2 teslamate[94614]:     vehicle_id: <censored>,
Jan 26 09:47:34 iot2 teslamate[94614]:     vin: <censored>,
Jan 26 09:47:34 iot2 teslamate[94614]:     tokens: [],
Jan 26 09:47:34 iot2 teslamate[94614]:     state: "unknown",
Jan 26 09:47:34 iot2 teslamate[94614]:     option_codes: [],
Jan 26 09:47:34 iot2 teslamate[94614]:     in_service: false,
Jan 26 09:47:34 iot2 teslamate[94614]:     display_name: nil,
Jan 26 09:47:34 iot2 teslamate[94614]:     color: nil,
Jan 26 09:47:34 iot2 teslamate[94614]:     calendar_enabled: nil,
Jan 26 09:47:34 iot2 teslamate[94614]:     backseat_token: nil,
Jan 26 09:47:34 iot2 teslamate[94614]:     backseat_token_updated_at: nil,
Jan 26 09:47:34 iot2 teslamate[94614]:     api_version: nil,
Jan 26 09:47:34 iot2 teslamate[94614]:     charge_state: nil,
Jan 26 09:47:34 iot2 teslamate[94614]:     climate_state: nil,
Jan 26 09:47:34 iot2 teslamate[94614]:     drive_state: nil,
Jan 26 09:47:34 iot2 teslamate[94614]:     gui_settings: nil,
Jan 26 09:47:34 iot2 teslamate[94614]:     vehicle_config: nil,
Jan 26 09:47:34 iot2 teslamate[94614]:     vehicle_state: nil
Jan 26 09:47:34 iot2 teslamate[94614]:   }
Jan 26 09:47:34 iot2 teslamate[94614]: ]
```

**Comment by virtualm2000** [comment]
> I think the solution would be something like:
> 
> ```diff
> diff --git a/lib/tesla_api/vehicle.ex b/lib/tesla_api/vehicle.ex
> index 9c25743d..c39c475b 100644
> --- a/lib/tesla_api/vehicle.ex
> +++ b/lib/tesla_api/vehicle.ex
> @@ -30,7 +30,7 @@ defmodule TeslaApi.Vehicle do
>        end
> 
>      TeslaApi.get(endpoint_url <> "/api/1/products", opts: [access_token: auth.token])
> -    |> handle_response(transform: &result/1)
> +    |> handle_response(transform: &list_result/1)
>    end
> 
>    def get(%Auth{} = auth, id) do
> @@ -61,6 +61,12 @@ defmodule TeslaApi.Vehicle do
>      |> handle_response(transform: &result/1)
>    end
> 
> +  def list_result(result) do
> +    result
> +    |> Enum.filter(fn(x) -> Map.has_key?(x, "vehicle_id") end)
> +    |> Enum.map(&result/1)
> +  end
> +
>    def result(v) do
>      %__MODULE__{
>        id: v["id"],
> @@ -88,7 +94,7 @@ defmodule TeslaApi.Vehicle do
>      case env do
>        %Tesla.Env{status: status, body: %{"response" => res}} when status in 200..299 ->
>          transform = Keyword.get(opts, :transform, & &1)
> -        {:ok, if(is_list(res), do: Enum.map(res, transform), else: transform.(res))}
> +        {:ok, transform.(res)}
> 
>        %Tesla.Env{status: 401} = env ->
>          {:error, %Error{reason: :unauthorized, env: env}}
> ```
> 
> This is a bit more invasive then I originally imagined, because originally the transform function was called for every element in the list, but this means we can't filter out list elements. So I changed the transform function to operate on the entire result. I think it should only get a list for the list API call, so this should be OK.
> 
> We could also do the filtering after the `handle_response` returns, but this is after we processed the result, which seems kind of yuck.

Tested and it works. No other products on my account but only cars.

**Comment by tb205gti** [comment]
This fixed my drives, did a quick'n'dirty edit as according to the PR and the last three drives where complete. I do not own other Tesla products, so cannot say if this brings adverse side effects if you have more products than cars.

**Comment by jolcese** [comment]
I do have a wall charger and vehicle. Tested this on a secondary install and works fine!

**Comment by shivaagarwal1** [comment]
Is there any way I can use this fix on Home Assistant Teslamate Add On?

https://github.com/matt-FFFFFF/hassio-addon-teslamate

**Comment by JakobLichterfeld** [comment]
> I do have a wall charger and vehicle. Tested this on a secondary install and works fine!
> 

Perfect, thanks for testing 🙏🏻

**Comment by ramonsmits** [comment]
FYI: Running this PR image since yesterday without issues. I only have a Tesla car.

**Comment by bikeymouse** [comment]
Hi,

I upgraded to 1.28.3 and things seem to be working fine, however I get warnings/errors (_"car_id=1 [error] Error / :unknown"_) in my log relating to the vehicle endpoint https://owner-api.teslamotors.com/api/1/vehicles/

I would expect everything would. be using the product endpoint now, is that correct?

```
2024-02-04 12:29:32.826 [info] Migrations already up
2024-02-04 12:29:34.998 [info] System Info: Erlang/OTP 26 (jit)
2024-02-04 12:29:34.998 [info] Version: 1.28.3
2024-02-04 12:29:35.637 [info] POST https://auth.tesla.com/oauth2/v3/token -> 200 (592.185 ms)
2024-02-04 12:29:35.637 [info] Refreshed api tokens
2024-02-04 12:29:35.641 [info] Scheduling token refresh in 6 h
2024-02-04 12:29:35.648 [info] Running TeslaMateWeb.Endpoint with cowboy 2.10.0 at :::4000 (http)
2024-02-04 12:29:35.649 [info] Access TeslaMateWeb.Endpoint at http://localhost
2024-02-04 12:29:36.045 [info] Starting logger for 'Anonimized'
2024-02-04 12:29:36.068 [info] MQTT connection has been established
2024-02-04 12:29:36.358 car_id=1 [info] Start / :online
2024-02-04 12:29:36.393 car_id=1 [info] Connecting ...
2024-02-04 12:30:15.475 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/149293xxxx/vehicle_data -> 408 (9079.515 ms)
2024-02-04 12:30:15.475 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2024-02-04 12:30:15.476 car_id=1 [error] Error / :unknown
2024-02-04 12:32:21.182 [info] GET https://owner-api.teslamotors.com/api/1/vehicles/1492931211761304/vehicle_data -> 408 (9073.748 ms)
2024-02-04 12:32:21.182 [warning] TeslaApi.Error / %{"error" => "{\"error\": \"timeout\"}", "error_description" => "", "response" => nil}
2024-02-04 12:32:21.182 car_id=1 [error] Error / :unknown
2024-02-04 12:32:48.632 car_id=1 [info] Suspending logging
2024-02-04 12:43:05.971 car_id=1 [info] Fetching vehicle state ...
2024-02-04 12:43:06.090 car_id=1 [info] Start / :asleep
2024-02-04 12:43:06.095 car_id=1 [info] Disconnecting ...

```
FYI 
I really removed all Teslamate containers and images re-downloading and recreating them with Docker-compose. 
Only the database-volume was re-used. Both this log and the UI show 1.28.3.

**Comment by JakobLichterfeld** [comment]
> I would expect everything would. be using the product endpoint now, is that correct?

no

**Comment by bikeymouse** [comment]
Yes you are right about the 408.  But still the https://owner-api.teslamotors.com/api/1/vehicles endpoint is used I thought that could no longer be used, or is that not correct?

**Comment by JakobLichterfeld** [comment]
> I thought that could no longer be used, or is that not correct?

Please stop asking these types of questions, or the access got really permitted.

**Comment by brianmay** [comment]
We need top be careful here, we want to ensure that that we are a welcoming community, and are open to feedback from everyone.

@bikeymouse The API call used above is `https://owner-api.teslamotors.com/api/1/vehicles/1492931211761304/vehicle_data` which is different from the `https://owner-api.teslamotors.com/api/1/vehicles` API call that we were forced to change.

The 408 error is the generic error that means your car is unreachable, e.g. maybe because it is asleep, or because it is outside network coverage, or something like that.

**Pull request merged**
