### PR TITLE
Change to dateTimeAsSystem and enable date formats

### PR DESCRIPTION
**Pull request by rikardronnkvist**
Gives the ability to have custom date formats on dashboards.

### CODE REVIEW

**Comment by rikardronnkvist** [comment]
https://github.com/adriankumpf/teslamate/discussions/3052

**Review by JakobLichterfeld — COMMENTED** [review]
Thanks for your PR.
lgtm, test needed

**Comment by DrMichael** [comment]
Happy to test that. @jlestel do we have a Grafana image for this PR?

**Comment by jlestel** [comment]
> Happy to test that. @jlestel do we have a Grafana image for this PR?

Not yet! CI fusion failed last night, we still need to take some time to test it.

I hope it will be possible soon!

**Comment by DrMichael** [comment]
Does it mean, you can set the date format with GF_DATE_FORMATS_FULL_DATE in your docker-compose.yaml?

**Comment by JakobLichterfeld** [comment]
Please update your branch

**Comment by JakobLichterfeld** [comment]
@swiffer is this still needed with our migration to latest grafana?

**Comment by swiffer** [comment]
there is an experimental browser locale based setting now

https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#use_browser_locale

before:
grafik

after:
grafik

grafik

i think we should make use of this instead. @jheredianet you have changed it already in your dashboards, right? could you consider changing it back if we go with an ENV setting instead in the grafana image?

https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/issues/16

**Comment by jheredianet** [comment]
> there is an experimental browser locale based setting now
> 
> https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#use_browser_locale
> 
> before: grafik
> 
> after: grafik
> 
> grafik
> 
> i think we should make use of this instead. @jheredianet you have changed it already in your dashboards, right? could you consider changing it back if we go with an ENV setting instead in the grafana image?
> 
> [jheredianet/Teslamate-CustomGrafanaDashboards#16](https://github.com/jheredianet/Teslamate-CustomGrafanaDashboards/issues/16)

Yes, I have. Sure, no problem. It's a good idea.

**Comment by JakobLichterfeld** [comment]
Close this, as replaced by #4064

**Pull request closed without merging**
